import {
  Building2,
  Camera,
  Car,
  Circle,
  CircleCheck,
  CircleDashed,
  CirclePause,
  CirclePlay,
  ClipboardCheck,
  Code2,
  Cpu,
  Fan,
  GraduationCap,
  Hammer,
  HardHat,
  Home,
  Network,
  Package,
  Palmtree,
  PencilRuler,
  Plane,
  ShieldAlert,
  ShieldCheck,
  ShieldX,
  Siren,
  Star,
  Thermometer,
  TriangleAlert,
  UserCog,
  Users,
  Wrench,
  type LucideIcon,
} from "lucide-react";

/** Kurowana lista ikon dostępnych w słownikach Planu Zasobów (nazwa kebab-case → komponent). */
export const ICON_OPTIONS: { value: string; icon: LucideIcon }[] = [
  { value: "circle", icon: Circle },
  { value: "hard-hat", icon: HardHat },
  { value: "code-2", icon: Code2 },
  { value: "wrench", icon: Wrench },
  { value: "user-cog", icon: UserCog },
  { value: "cpu", icon: Cpu },
  { value: "camera", icon: Camera },
  { value: "siren", icon: Siren },
  { value: "fan", icon: Fan },
  { value: "network", icon: Network },
  { value: "star", icon: Star },
  { value: "users", icon: Users },
  { value: "home", icon: Home },
  { value: "building-2", icon: Building2 },
  { value: "hammer", icon: Hammer },
  { value: "pencil-ruler", icon: PencilRuler },
  { value: "clipboard-check", icon: ClipboardCheck },
  { value: "circle-dashed", icon: CircleDashed },
  { value: "circle-play", icon: CirclePlay },
  { value: "triangle-alert", icon: TriangleAlert },
  { value: "circle-check", icon: CircleCheck },
  { value: "circle-pause", icon: CirclePause },
  { value: "shield-check", icon: ShieldCheck },
  { value: "shield-alert", icon: ShieldAlert },
  { value: "shield-x", icon: ShieldX },
  { value: "palmtree", icon: Palmtree },
  { value: "graduation-cap", icon: GraduationCap },
  { value: "thermometer", icon: Thermometer },
  { value: "plane", icon: Plane },
  { value: "package", icon: Package },
  { value: "car", icon: Car },
];

const ICON_BY_VALUE = new Map(ICON_OPTIONS.map((option) => [option.value, option.icon]));

export function resolveDictionaryIcon(value: string | null | undefined): LucideIcon {
  if (!value) return Circle;
  return ICON_BY_VALUE.get(value) ?? Circle;
}
