# -*- coding: utf-8 -*-
"""6 scenariuszy do walidacji Recommendation Engine.

Kody uslug zgodne z katalogiem v4.5. Kazdy scenariusz:
  - services: uslugi OBECNE w budynku + ich Functionality Level,
  - missing_applicable: uslugi TECHNICZNIE mozliwe, ale niezainstalowane
    (kandydaci do rozbudowy — rekomendacja typu 'expansion').
"""

REC_SCENARIOS = [
    {
        "id": 1,
        "title": "Budynek bez automatyki",
        "expectation": "wynik bliski 0% — rekomendacje powinny obejmowac praktycznie wszystkie obecne uslugi",
        "building_type": "non_residential",
        "climate_zone": "west_europe",
        "notes": "Instalacje HVAC/oswietlenia istnieja, ale bez zadnej automatyki (FL0).",
        "services": {
            "H-1a": 0, "H-2a": 0,
            "DHW-1b": 0,
            "C-1a": 0, "C-2a": 0,
            "V-1a": 0,
            "L-1a": 0,
        },
        "missing_applicable": [],
    },
    {
        "id": 2,
        "title": "Male biuro z harmonogramami",
        "expectation": "sredni wynik — braki w elastycznosci, raportowaniu, CO2",
        "building_type": "non_residential",
        "climate_zone": "west_europe",
        "notes": "Sterowanie czasowe i podzial na strefy. Brak monitoringu energii, alarmow, CO2, elastycznosci.",
        "services": {
            "H-1a": 2, "H-1c": 2, "H-2a": 2,
            "DHW-1b": 2,
            "C-1a": 2, "C-2a": 2,
            "V-1a": 2, "V-2d": 1,
            "L-1a": 2, "L-2": 2,
            "DE-1": 2,
        },
        "missing_applicable": ["H-3", "V-6"],
    },
    {
        "id": 3,
        "title": "Sklep typu Decathlon (Loxone/BACnet/Modbus)",
        "expectation": "wynik dobry — braki w PV/magazynie/EV oraz pelnej elastycznosci",
        "building_type": "non_residential",
        "climate_zone": "west_europe",
        "notes": "HVAC, oswietlenie, liczniki, dashboard, alarmy, raportowanie. Brak PV/magazynu/EV.",
        "services": {
            "H-1a": 3, "H-1c": 2, "H-2a": 2, "H-3": 3,
            "DHW-1b": 2, "DHW-3": 3,
            "C-1a": 3, "C-2a": 2, "C-3": 3,
            "V-1a": 3, "V-1c": 2, "V-6": 2,
            "L-1a": 3, "L-2": 3,
            "DE-1": 2,
            "E-12": 3,
            "MC-3": 3, "MC-4": 2, "MC-13": 3, "MC-30": 3,
        },
        "missing_applicable": ["E-2", "H-4"],
    },
    {
        "id": 4,
        "title": "Nowoczesny biurowiec z BMS (bez PV/EV/magazynu)",
        "expectation": "wynik wysoki — glowne braki w elastycznosci energetycznej (H-4/C-4)",
        "building_type": "non_residential",
        "climate_zone": "west_europe",
        "notes": "Pelny BMS, wysokie poziomy HVAC/oswietlenia/rolet/monitoringu. Brak domeny elektrycznej (PV/magazyn/EV).",
        "services": {
            "H-1a": 4, "H-1c": 2, "H-1d": 3, "H-2b": 2, "H-2d": 4, "H-3": 4, "H-4": 2,
            "DHW-1b": 3, "DHW-2b": 3, "DHW-3": 4,
            "C-1a": 4, "C-1d": 3, "C-2a": 3, "C-2b": 4, "C-3": 4, "C-4": 2,
            "V-1a": 4, "V-1c": 3, "V-2d": 3, "V-3": 2, "V-6": 3,
            "L-1a": 3, "L-2": 4,
            "DE-1": 4, "DE-2": 2, "DE-4": 4,
            "MC-3": 3, "MC-4": 3, "MC-9": 2, "MC-13": 3, "MC-30": 3,
        },
        "missing_applicable": ["E-2", "E-3", "EV-15"],
    },
    {
        "id": 5,
        "title": "Budynek z PV i EV, ale bez magazynu energii",
        "expectation": "rekomendacje powinny wskazac magazyn energii (E-3) i optymalizacje autokonsumpcji",
        "building_type": "non_residential",
        "climate_zone": "west_europe",
        "notes": "PV monitorowane, ladowarki EV obecne. Brak magazynu energii (E-3) i slaba autokonsumpcja (E-4).",
        "services": {
            "H-1a": 2, "H-1c": 2, "H-2a": 2, "H-3": 2,
            "C-1a": 2, "C-2a": 2,
            "V-1a": 2, "V-6": 2,
            "L-1a": 2, "L-2": 2,
            "DE-1": 2,
            "E-2": 4, "E-4": 1, "E-12": 2,
            "EV-15": 2, "EV-17": 2,
            "MC-3": 2, "MC-13": 2,
        },
        "missing_applicable": ["E-3"],
    },
    {
        "id": 6,
        "title": "Budynek z dobrym HVAC, ale slabym monitoringiem energii",
        "expectation": "rekomendacje na gorze powinny dotyczyc raportowania/pomiaru energii, nie HVAC",
        "building_type": "non_residential",
        "climate_zone": "west_europe",
        "notes": "HVAC na wysokich poziomach, ale raportowanie i pomiar energii szczatkowe (H-3/C-3/E-12/MC-13/MC-4 niskie).",
        "services": {
            "H-1a": 4, "H-1c": 2, "H-2b": 3, "H-2d": 3, "H-3": 1,
            "DHW-1b": 3, "DHW-3": 1,
            "C-1a": 4, "C-2a": 3, "C-3": 1,
            "V-1a": 4, "V-1c": 3, "V-2d": 3, "V-6": 2,
            "L-1a": 3, "L-2": 4,
            "DE-1": 3,
            "E-12": 1,
            "MC-3": 2, "MC-4": 1, "MC-13": 1,
        },
        "missing_applicable": [],
    },
]
