# -*- coding: utf-8 -*-
"""SRI Dependency Engine — dane zrodlowe.

Warstwa POMOCNICZA nad oficjalna metodologia SRI. NIE zmienia punktacji ani listy uslug.
- CAPABILITIES: kanoniczny katalog funkcji/zdolnosci technicznych.
- SERVICE_DEPS: mapowanie capability -> usluga z (min_level, source_type).
    min_level = najnizszy Functionality Level, od ktorego dana zdolnosc jest wymagana.
    source_type: 'M' = official_methodology (wynika wprost z opisu FL/metodologii),
                 'E' = engineering_assumption (praktyczna zaleznosc techniczna).
- CROSS_DOMAIN: funkcje wspolne dla wielu domen.
"""

SRC = {"M": "official_methodology", "E": "engineering_assumption"}

# ─────────────────────────────────────────────────────────────────────────────
# Katalog capabilities
# category: sensing | control | communication | metering | flexibility | actuation | reporting | safety
# verification_mode: automatic (system potwierdzi z danych BMS) | assisted (dane + potwierdzenie czlowieka) | manual (obecnosc fizyczna/zdjecie/dokument)
# ─────────────────────────────────────────────────────────────────────────────
CAPABILITIES = {
    "temperature_measurement": {
        "name_pl": "Pomiar temperatury", "category": "sensing",
        "description": "Pomiar temperatury pomieszczen/mediow niezbedny do regulacji.",
        "evidence": ["odczyt z BMS", "lista czujnikow", "zdjecie instalacji"],
        "verification": "Sprawdz obecnosc i wiarygodnosc punktow pomiaru temperatury w BMS.",
        "verification_mode": "assisted",
    },
    "occupancy_detection": {
        "name_pl": "Detekcja obecnosci", "category": "sensing",
        "description": "Wykrywanie obecnosci/zajetosci osob w strefie.",
        "evidence": ["odczyt z BMS", "lista czujnikow PIR/obecnosci", "zdjecie instalacji"],
        "verification": "Sprawdz czujniki obecnosci i ich powiazanie z logika sterowania.",
        "verification_mode": "assisted",
    },
    "co2_measurement": {
        "name_pl": "Pomiar CO2 / jakosci powietrza", "category": "sensing",
        "description": "Pomiar CO2 (opcjonalnie VOC) na potrzeby wentylacji na zadanie i IAQ.",
        "evidence": ["odczyt z BMS", "lista czujnikow CO2", "certyfikat/kalibracja"],
        "verification": "Sprawdz obecnosc czujnikow CO2 w reprezentatywnych strefach i ich dryft.",
        "verification_mode": "assisted",
    },
    "humidity_measurement": {
        "name_pl": "Pomiar wilgotnosci", "category": "sensing",
        "description": "Pomiar wilgotnosci (m.in. do free-coolingu entalpiowego i ochrony antykondensacyjnej).",
        "evidence": ["odczyt z BMS", "lista czujnikow"],
        "verification": "Sprawdz punkty pomiaru wilgotnosci i ich wykorzystanie w logice.",
        "verification_mode": "assisted",
    },
    "daylight_measurement": {
        "name_pl": "Pomiar natezenia swiatla", "category": "sensing",
        "description": "Pomiar luksow do sterowania oswietleniem wg swiatla dziennego.",
        "evidence": ["odczyt z systemu oswietlenia", "lista czujnikow luksowych"],
        "verification": "Sprawdz czujniki luksowe w strefach przyokiennych i ich kalibracje.",
        "verification_mode": "assisted",
    },
    "weather_data": {
        "name_pl": "Dane pogodowe / prognoza", "category": "sensing",
        "description": "Temperatura zewnetrzna i/lub prognoza pogody dla kompensacji i predykcji.",
        "evidence": ["konfiguracja stacji pogodowej/feedu", "odczyt z BMS"],
        "verification": "Sprawdz zrodlo danych pogodowych i jego uzycie w krzywych/predykcji.",
        "verification_mode": "automatic",
    },
    "central_automatic_control": {
        "name_pl": "Centralne sterowanie automatyczne", "category": "control",
        "description": "Automatyczna regulacja na poziomie centralnym (np. termostat centralny).",
        "evidence": ["konfiguracja sterownika/BMS", "odczyt z BMS"],
        "verification": "Sprawdz obecnosc automatycznej regulacji zamiast sterowania recznego.",
        "verification_mode": "assisted",
    },
    "zonal_control": {
        "name_pl": "Sterowanie strefowe / indywidualne", "category": "control",
        "description": "Niezalezna regulacja pomieszczen/stref.",
        "evidence": ["nastawy per strefa w BMS", "schemat stref", "zdjecia sterownikow"],
        "verification": "Sprawdz niezalezne zadawanie parametrow dla stref/pomieszczen.",
        "verification_mode": "assisted",
    },
    "scheduling": {
        "name_pl": "Harmonogramy czasowe", "category": "control",
        "description": "Sterowanie wg harmonogramow dobowych/tygodniowych/kalendarza.",
        "evidence": ["konfiguracja harmonogramow w BMS", "zrzut ekranu"],
        "verification": "Sprawdz istnienie i aktualnosc harmonogramow pracy.",
        "verification_mode": "assisted",
    },
    "demand_based_control": {
        "name_pl": "Sterowanie wg zapotrzebowania", "category": "control",
        "description": "Regulacja wg rzeczywistego zapotrzebowania (obciazenie, sygnaly stref, IAQ).",
        "evidence": ["konfiguracja logiki w BMS", "trendy nastaw vs zapotrzebowanie"],
        "verification": "Sprawdz, czy nastawy zmieniaja sie wg zapotrzebowania, nie na stalo.",
        "verification_mode": "assisted",
    },
    "predictive_control": {
        "name_pl": "Sterowanie predykcyjne / optymalizacja", "category": "control",
        "description": "Optymalizacja z wyprzedzeniem (pogoda, oblozenie, ceny) i/lub adaptacyjna.",
        "evidence": ["opis logiki optymalizacji", "konfiguracja BMS/platformy", "trendy"],
        "verification": "Sprawdz realne uzycie predykcji/optymalizacji (nie tylko harmonogram).",
        "verification_mode": "assisted",
    },
    "interlock_control": {
        "name_pl": "Blokada/koordynacja trybow (interlock)", "category": "control",
        "description": "Logika uniemozliwiajaca jednoczesne grzanie i chlodzenie (dead-band).",
        "evidence": ["konfiguracja dead-band/interlock", "trendy trybow H/C"],
        "verification": "Sprawdz martwa strefe i brak jednoczesnej pracy grzanie/chlodzenie.",
        "verification_mode": "assisted",
    },
    "sequencing_controller": {
        "name_pl": "Sterownik kaskady/sekwencji zrodel", "category": "control",
        "description": "Koordynacja kilku zrodel (kolejnosc, priorytety, rownowazenie pracy).",
        "evidence": ["konfiguracja kaskady w BMS", "trendy udzialu zrodel"],
        "verification": "Sprawdz logike sekwencjonowania i kryteria przelaczania zrodel.",
        "verification_mode": "assisted",
    },
    "modulating_generator": {
        "name_pl": "Modulacja mocy zrodla", "category": "control",
        "description": "Zrodlo (kociol/PC/agregat/CHP) z regulowana moca zamiast on/off.",
        "evidence": ["DTR/tabliczka zrodla", "trendy modulacji", "zdjecie instalacji"],
        "verification": "Sprawdz zdolnosc modulacji mocy i jej wykorzystanie.",
        "verification_mode": "manual",
    },
    "variable_speed_drive": {
        "name_pl": "Naped o zmiennej predkosci (falownik)", "category": "control",
        "description": "Pompy/wentylatory z regulacja predkosci (falownik).",
        "evidence": ["DTR pomp/wentylatorow", "trendy predkosci/mocy", "zdjecie falownika"],
        "verification": "Sprawdz obecnosc falownikow i tryb regulacji (nie stala predkosc).",
        "verification_mode": "manual",
    },
    "digital_communication": {
        "name_pl": "Komunikacja cyfrowa sterownikow", "category": "communication",
        "description": "Sterowniki komunikuja sie miedzy soba (magistrala/protokol), nie punkt-punkt.",
        "evidence": ["schemat magistrali (KNX/BACnet/Modbus)", "lista urzadzen na magistrali"],
        "verification": "Sprawdz integracje cyfrowa sterownikow (protokol, komunikacja).",
        "verification_mode": "assisted",
    },
    "bms_integration": {
        "name_pl": "Integracja z BMS/BACS", "category": "communication",
        "description": "Podlaczenie do nadrzednego systemu zarzadzania budynkiem.",
        "evidence": ["architektura BMS", "zrzut ekranu z punktami", "lista integracji"],
        "verification": "Sprawdz widocznosc i sterowalnosc uslugi z poziomu BMS.",
        "verification_mode": "assisted",
    },
    "remote_access": {
        "name_pl": "Zdalny dostep", "category": "communication",
        "description": "Zdalny podglad/sterowanie i zarzadzanie (VPN/chmura/portal).",
        "evidence": ["konfiguracja dostepu zdalnego", "zrzut portalu/aplikacji"],
        "verification": "Sprawdz mozliwosc bezpiecznego zdalnego dostepu do systemu.",
        "verification_mode": "assisted",
    },
    "energy_metering": {
        "name_pl": "Pomiar energii/ciepla/chlodu", "category": "metering",
        "description": "Liczniki energii, ciepla lub chlodu dla monitoringu i raportowania.",
        "evidence": ["lista licznikow", "odczyt z BMS", "zdjecie licznikow"],
        "verification": "Sprawdz obecnosc licznikow i archiwizacje danych zuzycia.",
        "verification_mode": "assisted",
    },
    "submetering": {
        "name_pl": "Podlicznikowanie (submetering)", "category": "metering",
        "description": "Opomiarowanie poszczegolnych obwodow/odbiorow.",
        "evidence": ["schemat opomiarowania obwodow", "lista podlicznikow"],
        "verification": "Sprawdz zakres submeteringu kluczowych odbiorow.",
        "verification_mode": "assisted",
    },
    "pv_monitoring": {
        "name_pl": "Monitoring produkcji PV/OZE", "category": "metering",
        "description": "Pomiar i monitoring produkcji lokalnej (falowniki/liczniki).",
        "evidence": ["monitoring falownikow", "dashboard produkcji", "lista falownikow"],
        "verification": "Sprawdz monitoring produkcji (najlepiej per string/falownik).",
        "verification_mode": "assisted",
    },
    "bidirectional_metering": {
        "name_pl": "Pomiar dwukierunkowy", "category": "metering",
        "description": "Licznik dwukierunkowy (pobor/oddanie) — warunek uslug sieciowych.",
        "evidence": ["DTR/tabliczka licznika", "odczyt z systemu", "umowa dystrybucyjna"],
        "verification": "Sprawdz obecnosc pomiaru dwukierunkowego i jego dane.",
        "verification_mode": "assisted",
    },
    "reporting_platform": {
        "name_pl": "Platforma raportowania/wizualizacji", "category": "reporting",
        "description": "Prezentacja stanu i danych (dashboardy/wizualizacja).",
        "evidence": ["zrzut dashboardu", "dostep do platformy"],
        "verification": "Sprawdz dostepnosc platformy prezentujacej dane uslugi.",
        "verification_mode": "automatic",
    },
    "data_logging": {
        "name_pl": "Rejestracja i historia danych (trendy)", "category": "reporting",
        "description": "Archiwizacja danych historycznych (trendy) do analizy.",
        "evidence": ["eksport trendow", "konfiguracja historiana"],
        "verification": "Sprawdz archiwizacje danych i dostepnosc historii/trendow.",
        "verification_mode": "automatic",
    },
    "fault_detection": {
        "name_pl": "Wykrywanie usterek (FDD)", "category": "reporting",
        "description": "Automatyczne wykrywanie odchylen/usterek i wsparcie diagnozy.",
        "evidence": ["lista regul FDD", "raporty wykrytych usterek"],
        "verification": "Sprawdz reguly FDD wykrywajace odchylenia (nie tylko awarie).",
        "verification_mode": "assisted",
    },
    "alarms": {
        "name_pl": "Alarmy i powiadomienia", "category": "reporting",
        "description": "Alarmy progowe/awaryjne z powiadomieniami.",
        "evidence": ["lista alarmow", "konfiguracja powiadomien"],
        "verification": "Sprawdz konfiguracje alarmow i sciezke powiadomien.",
        "verification_mode": "automatic",
    },
    "actuator_feedback": {
        "name_pl": "Informacja zwrotna z napedow", "category": "reporting",
        "description": "Napedy raportuja pozycje/stan (do monitoringu i diagnostyki).",
        "evidence": ["konfiguracja informacji zwrotnej", "trendy pozycji"],
        "verification": "Sprawdz, czy napedy zwracaja pozycje/stan do systemu.",
        "verification_mode": "assisted",
    },
    "thermal_storage": {
        "name_pl": "Magazyn ciepla/chlodu (bufor/TES)", "category": "flexibility",
        "description": "Zasobnik buforowy lub magazyn chlodu ze sterowaniem ladowania.",
        "evidence": ["schemat hydrauliczny z buforem", "zdjecie zbiornika", "DTR"],
        "verification": "Sprawdz obecnosc magazynu i logike jego ladowania/rozladowania.",
        "verification_mode": "manual",
    },
    "electrical_storage": {
        "name_pl": "Magazyn energii elektrycznej", "category": "flexibility",
        "description": "Bateria/BESS ze sterowaniem ladowania/rozladowania.",
        "evidence": ["DTR magazynu", "konfiguracja EMS", "zdjecie instalacji"],
        "verification": "Sprawdz obecnosc magazynu energii i strategie sterowania.",
        "verification_mode": "manual",
    },
    "local_generation": {
        "name_pl": "Lokalna generacja (PV/CHP)", "category": "flexibility",
        "description": "Zrodlo lokalne energii elektrycznej (PV, kogeneracja).",
        "evidence": ["DTR instalacji PV/CHP", "zdjecie", "schemat elektryczny"],
        "verification": "Sprawdz obecnosc i moc lokalnej generacji.",
        "verification_mode": "manual",
    },
    "solar_thermal_collector": {
        "name_pl": "Kolektory sloneczne (solar thermal)", "category": "flexibility",
        "description": "Instalacja solarna do przygotowania CWU/ciepla.",
        "evidence": ["schemat instalacji solarnej", "zdjecie kolektorow", "DTR"],
        "verification": "Sprawdz obecnosc kolektorow i logike priorytetu solarnego.",
        "verification_mode": "manual",
    },
    "self_consumption_optimization": {
        "name_pl": "Optymalizacja autokonsumpcji", "category": "flexibility",
        "description": "Sterowanie odbiornikami wg biezacej produkcji lokalnej (nadwyzka PV).",
        "evidence": ["konfiguracja EMS/priorytetow", "trendy autokonsumpcji"],
        "verification": "Sprawdz reakcje odbiornikow na nadwyzke produkcji.",
        "verification_mode": "assisted",
    },
    "grid_signal_interface": {
        "name_pl": "Interfejs sygnalow sieci/taryf", "category": "flexibility",
        "description": "Odbior sygnalow taryf/DSM/smart grid i reakcja odbiorow/zrodel.",
        "evidence": ["konfiguracja taryf/OpenADR/SG-Ready", "trendy poboru vs sygnaly"],
        "verification": "Sprawdz realny odbior sygnalow i reakcje (nie sama deklaracja).",
        "verification_mode": "assisted",
    },
    "microgrid_controller": {
        "name_pl": "Kontroler mikrosieci / praca wyspowa", "category": "flexibility",
        "description": "Sterowanie trybami sieci (on/off-grid), koordynacja zrodel/magazynu.",
        "evidence": ["schemat microgrid/SZR", "konfiguracja kontrolera", "testy przelaczania"],
        "verification": "Sprawdz zdolnosc pracy wyspowej i koordynacje zrodel.",
        "verification_mode": "manual",
    },
    "dsm_override": {
        "name_pl": "Nadrzedne sterowanie DSM (override)", "category": "safety",
        "description": "Mozliwosc nadpisania automatyki DSM z zachowaniem priorytetow.",
        "evidence": ["konfiguracja override/priorytetow", "logi override"],
        "verification": "Sprawdz mozliwosc i granularnosc override oraz rejestracje.",
        "verification_mode": "assisted",
    },
    "heat_recovery_control": {
        "name_pl": "Sterowanie odzyskiem ciepla (by-pass)", "category": "control",
        "description": "Regulacja wymiennika odzysku z by-passem i ochrona przed przegrzewem.",
        "evidence": ["DTR centrali z odzyskiem", "konfiguracja by-passu", "trendy"],
        "verification": "Sprawdz obecnosc odzysku, by-passu i logiki ochrony.",
        "verification_mode": "manual",
    },
    "free_cooling": {
        "name_pl": "Free-cooling", "category": "control",
        "description": "Chlodzenie powietrzem/woda zewnetrzna zamiast agregatu (economizer).",
        "evidence": ["konfiguracja economizera", "trendy przepustnic/temperatur"],
        "verification": "Sprawdz logike free-coolingu i jej realne dzialanie.",
        "verification_mode": "assisted",
    },
    "automated_switching_actuation": {
        "name_pl": "Automatyczne zalaczanie/wylaczanie", "category": "actuation",
        "description": "Wykonawcze zalaczanie/wylaczanie (np. oswietlenia) wg logiki.",
        "evidence": ["schemat sterowania", "zdjecie sterownikow/przekaznikow"],
        "verification": "Sprawdz elementy wykonawcze zalaczania/wylaczania.",
        "verification_mode": "assisted",
    },
    "dimmable_lighting": {
        "name_pl": "Oprawy scieramialne (dimming)", "category": "actuation",
        "description": "Oprawy z plynna regulacja mocy (np. DALI).",
        "evidence": ["schemat DALI", "lista opraw", "zdjecie instalacji"],
        "verification": "Sprawdz obecnosc opraw scieramialnych i regulacje plynna.",
        "verification_mode": "manual",
    },
    "shading_actuation": {
        "name_pl": "Napedy zacienienia/rolet", "category": "actuation",
        "description": "Zmotoryzowane oslony (rolety/zaluzje/markizy) ze sterowaniem.",
        "evidence": ["schemat sterowania oslonami", "zdjecie napedow", "DTR"],
        "verification": "Sprawdz obecnosc napedow oslon i ich sterowanie.",
        "verification_mode": "manual",
    },
    "sun_position_tracking": {
        "name_pl": "Sledzenie pozycji slonca", "category": "control",
        "description": "Sterowanie oslonami wg pozycji slonca i ochrona przed olsnieniem.",
        "evidence": ["konfiguracja logiki pozycji slonca", "trendy pozycji oslon"],
        "verification": "Sprawdz logike wg azymutu/wysokosci slonca.",
        "verification_mode": "assisted",
    },
    "window_contact": {
        "name_pl": "Detekcja otwarcia okna", "category": "sensing",
        "description": "Kontaktrony okienne do blokady HVAC/koordynacji przewietrzania.",
        "evidence": ["schemat kontaktronow", "odczyt stanu okien", "zdjecie"],
        "verification": "Sprawdz detekcje otwarcia okien i powiazanie z HVAC.",
        "verification_mode": "assisted",
    },
    "window_actuation": {
        "name_pl": "Napedy okien/klap", "category": "actuation",
        "description": "Zmotoryzowane okna/klapy do sterowanego przewietrzania.",
        "evidence": ["schemat napedow okien", "zdjecie silownikow", "DTR"],
        "verification": "Sprawdz obecnosc napedow okien/klap i ich sterowanie.",
        "verification_mode": "manual",
    },
    "ev_charging_point": {
        "name_pl": "Punkt ladowania EV", "category": "actuation",
        "description": "Stacja ladowania pojazdow elektrycznych (AC/DC).",
        "evidence": ["DTR stacji", "zdjecie", "schemat przylacza"],
        "verification": "Sprawdz obecnosc, liczbe i moc punktow ladowania.",
        "verification_mode": "manual",
    },
    "load_balancing": {
        "name_pl": "Zarzadzanie moca ladowania (load balancing)", "category": "flexibility",
        "description": "Dynamiczny rozdzial mocy miedzy punkty EV i odbiory (ochrona przylacza).",
        "evidence": ["konfiguracja load balancing/OCPP", "trendy mocy vs limit przylacza"],
        "verification": "Sprawdz dzialanie load balancingu wzgledem mocy przylacza.",
        "verification_mode": "assisted",
    },
    "charging_connectivity": {
        "name_pl": "Laczonosc ladowania (OCPP/backend)", "category": "communication",
        "description": "Komunikacja stacji EV (OCPP), autoryzacja, rozliczenia.",
        "evidence": ["konfiguracja OCPP/backendu", "raporty sesji"],
        "verification": "Sprawdz laczonosc stacji i integracje z backendem.",
        "verification_mode": "assisted",
    },
}

# ─────────────────────────────────────────────────────────────────────────────
# Mapowanie: usluga -> [(capability_id, min_level, source_code)]
# ─────────────────────────────────────────────────────────────────────────────
SERVICE_DEPS = {
    # ── Heating ──────────────────────────────────────────────────────────────
    "H-1a": [("central_automatic_control", 1, "M"), ("temperature_measurement", 1, "E"),
             ("zonal_control", 2, "M"), ("digital_communication", 3, "M"),
             ("bms_integration", 3, "M"), ("occupancy_detection", 4, "M")],
    "H-1b": [("central_automatic_control", 1, "M"), ("temperature_measurement", 1, "E"),
             ("zonal_control", 2, "M"), ("demand_based_control", 2, "E"),
             ("predictive_control", 3, "M"), ("weather_data", 3, "E")],
    "H-1c": [("weather_data", 1, "M"), ("temperature_measurement", 1, "E"),
             ("demand_based_control", 2, "M")],
    "H-1d": [("demand_based_control", 1, "M"), ("variable_speed_drive", 2, "M"),
             ("digital_communication", 4, "M")],
    "H-1f": [("thermal_storage", 1, "M"), ("scheduling", 1, "E"), ("temperature_measurement", 1, "E"),
             ("demand_based_control", 2, "M"), ("grid_signal_interface", 3, "M")],
    "H-2a": [("modulating_generator", 1, "M"), ("weather_data", 1, "E"),
             ("demand_based_control", 2, "M"), ("bms_integration", 2, "E")],
    "H-2b": [("modulating_generator", 1, "M"), ("weather_data", 1, "E"),
             ("demand_based_control", 2, "M"), ("temperature_measurement", 2, "E"),
             ("predictive_control", 3, "M"), ("grid_signal_interface", 3, "E"), ("thermal_storage", 3, "E")],
    "H-2d": [("sequencing_controller", 1, "M"), ("energy_metering", 2, "M"),
             ("grid_signal_interface", 3, "M"), ("predictive_control", 4, "M"), ("weather_data", 4, "E")],
    "H-3": [("reporting_platform", 1, "M"), ("data_logging", 2, "M"), ("energy_metering", 2, "M"),
            ("fault_detection", 3, "E"), ("alarms", 3, "M"), ("predictive_control", 4, "M")],
    "H-4": [("grid_signal_interface", 1, "M"), ("scheduling", 1, "E"), ("thermal_storage", 2, "E"),
            ("predictive_control", 3, "M"), ("bidirectional_metering", 4, "M")],
    # ── Domestic hot water ───────────────────────────────────────────────────
    "DHW-1a": [("temperature_measurement", 1, "E"), ("scheduling", 1, "M"),
               ("demand_based_control", 2, "M"), ("grid_signal_interface", 3, "M"),
               ("self_consumption_optimization", 3, "E")],
    "DHW-1b": [("temperature_measurement", 1, "E"), ("scheduling", 1, "M"),
               ("demand_based_control", 2, "M"), ("grid_signal_interface", 3, "M")],
    "DHW-1d": [("solar_thermal_collector", 1, "M"), ("temperature_measurement", 1, "E"),
               ("demand_based_control", 2, "M"), ("predictive_control", 3, "M"), ("weather_data", 3, "E")],
    "DHW-2b": [("sequencing_controller", 1, "M"), ("energy_metering", 2, "M"),
               ("grid_signal_interface", 3, "M"), ("predictive_control", 4, "M")],
    "DHW-3": [("reporting_platform", 1, "M"), ("energy_metering", 1, "E"), ("data_logging", 2, "M"),
              ("fault_detection", 3, "E"), ("alarms", 3, "M"), ("predictive_control", 4, "M")],
    # ── Cooling ──────────────────────────────────────────────────────────────
    "C-1a": [("central_automatic_control", 1, "M"), ("temperature_measurement", 1, "E"),
             ("zonal_control", 2, "M"), ("digital_communication", 3, "M"),
             ("bms_integration", 3, "M"), ("occupancy_detection", 4, "M")],
    "C-1b": [("central_automatic_control", 1, "M"), ("temperature_measurement", 1, "E"),
             ("humidity_measurement", 1, "E"), ("zonal_control", 2, "M"),
             ("predictive_control", 3, "M"), ("weather_data", 3, "E")],
    "C-1c": [("weather_data", 1, "M"), ("temperature_measurement", 1, "E"),
             ("demand_based_control", 2, "M")],
    "C-1d": [("demand_based_control", 1, "M"), ("variable_speed_drive", 2, "M"),
             ("digital_communication", 4, "M")],
    "C-1f": [("interlock_control", 1, "M"), ("temperature_measurement", 1, "E"),
             ("bms_integration", 2, "M")],
    "C-1g": [("thermal_storage", 1, "M"), ("scheduling", 1, "E"), ("temperature_measurement", 1, "E"),
             ("demand_based_control", 2, "M"), ("grid_signal_interface", 3, "M")],
    "C-2a": [("modulating_generator", 1, "M"), ("weather_data", 1, "E"),
             ("demand_based_control", 2, "M"), ("predictive_control", 3, "M"), ("free_cooling", 3, "E")],
    "C-2b": [("sequencing_controller", 1, "M"), ("energy_metering", 2, "M"),
             ("grid_signal_interface", 3, "M"), ("predictive_control", 4, "M")],
    "C-3": [("reporting_platform", 1, "M"), ("data_logging", 2, "M"), ("energy_metering", 2, "M"),
            ("fault_detection", 3, "E"), ("alarms", 3, "M"), ("predictive_control", 4, "M")],
    "C-4": [("grid_signal_interface", 1, "M"), ("scheduling", 1, "E"), ("thermal_storage", 2, "E"),
            ("predictive_control", 3, "M"), ("bidirectional_metering", 4, "M")],
    # ── Ventilation ──────────────────────────────────────────────────────────
    "V-1a": [("scheduling", 1, "M"), ("demand_based_control", 1, "E"), ("occupancy_detection", 2, "M"),
             ("co2_measurement", 3, "M"), ("digital_communication", 4, "M"), ("bms_integration", 4, "M")],
    "V-1c": [("demand_based_control", 1, "M"), ("variable_speed_drive", 2, "M"),
             ("digital_communication", 3, "M"), ("bms_integration", 4, "E")],
    "V-2c": [("heat_recovery_control", 1, "M"), ("temperature_measurement", 1, "E"), ("free_cooling", 2, "M")],
    "V-2d": [("weather_data", 1, "M"), ("temperature_measurement", 1, "E"),
             ("demand_based_control", 2, "M"), ("predictive_control", 3, "M")],
    "V-3": [("free_cooling", 1, "M"), ("temperature_measurement", 1, "E"),
            ("humidity_measurement", 2, "M"), ("predictive_control", 3, "M")],
    "V-6": [("co2_measurement", 1, "M"), ("reporting_platform", 1, "M"),
            ("data_logging", 2, "M"), ("alarms", 3, "M")],
    # ── Lighting ─────────────────────────────────────────────────────────────
    "L-1a": [("occupancy_detection", 1, "M"), ("automated_switching_actuation", 2, "M"),
             ("digital_communication", 3, "M"), ("zonal_control", 3, "E")],
    "L-2": [("daylight_measurement", 1, "M"), ("automated_switching_actuation", 1, "E"),
            ("dimmable_lighting", 2, "M"), ("zonal_control", 3, "M"), ("digital_communication", 4, "M")],
    # ── Dynamic building envelope ─────────────────────────────────────────────
    "DE-1": [("shading_actuation", 1, "M"), ("weather_data", 1, "M"), ("temperature_measurement", 2, "E"),
             ("zonal_control", 2, "E"), ("sun_position_tracking", 3, "M"),
             ("bms_integration", 4, "M"), ("predictive_control", 4, "M")],
    "DE-2": [("window_contact", 1, "M"), ("bms_integration", 1, "E"),
             ("window_actuation", 2, "M"), ("predictive_control", 3, "M")],
    "DE-4": [("actuator_feedback", 1, "M"), ("reporting_platform", 1, "M"), ("data_logging", 2, "M"),
             ("fault_detection", 3, "E"), ("alarms", 3, "M"), ("predictive_control", 4, "M")],
    # ── Electricity ──────────────────────────────────────────────────────────
    "E-2": [("pv_monitoring", 1, "M"), ("reporting_platform", 1, "M"), ("data_logging", 2, "M"),
            ("alarms", 3, "M"), ("predictive_control", 4, "M")],
    "E-3": [("electrical_storage", 1, "M"), ("grid_signal_interface", 2, "M"),
            ("self_consumption_optimization", 2, "E"), ("bidirectional_metering", 3, "M"),
            ("predictive_control", 4, "M")],
    "E-4": [("self_consumption_optimization", 1, "M"), ("local_generation", 1, "E"),
            ("bms_integration", 2, "M"), ("predictive_control", 3, "M")],
    "E-5": [("modulating_generator", 1, "M"), ("local_generation", 1, "E"),
            ("grid_signal_interface", 2, "M"), ("thermal_storage", 2, "E")],
    "E-8": [("grid_signal_interface", 1, "M"), ("electrical_storage", 2, "E"),
            ("microgrid_controller", 2, "M"), ("predictive_control", 3, "M")],
    "E-11": [("electrical_storage", 1, "E"), ("reporting_platform", 1, "M"), ("data_logging", 2, "M"),
             ("alarms", 3, "M"), ("predictive_control", 4, "M")],
    "E-12": [("energy_metering", 1, "M"), ("reporting_platform", 1, "M"), ("data_logging", 2, "M"),
             ("submetering", 3, "M"), ("alarms", 3, "E"), ("predictive_control", 4, "M")],
    # ── Electric vehicle charging ─────────────────────────────────────────────
    "EV-15": [("ev_charging_point", 1, "M"), ("scheduling", 2, "M"), ("load_balancing", 3, "M"),
              ("self_consumption_optimization", 4, "E"), ("grid_signal_interface", 4, "E")],
    "EV-16": [("grid_signal_interface", 1, "M"), ("bidirectional_metering", 2, "M")],
    "EV-17": [("reporting_platform", 1, "M"), ("charging_connectivity", 2, "M"), ("remote_access", 2, "E")],
    # ── Monitoring & control ─────────────────────────────────────────────────
    "MC-3": [("scheduling", 1, "M"), ("predictive_control", 2, "M"), ("weather_data", 2, "E"),
             ("occupancy_detection", 3, "M")],
    "MC-4": [("alarms", 1, "M"), ("fault_detection", 2, "M"), ("reporting_platform", 3, "E"),
             ("remote_access", 3, "E")],
    "MC-9": [("occupancy_detection", 1, "M"), ("digital_communication", 2, "M"), ("bms_integration", 2, "M")],
    "MC-13": [("reporting_platform", 1, "M"), ("bms_integration", 1, "E"), ("energy_metering", 2, "M"),
              ("data_logging", 2, "M"), ("fault_detection", 3, "E"), ("alarms", 3, "M")],
    "MC-25": [("grid_signal_interface", 1, "M"), ("bidirectional_metering", 2, "M")],
    "MC-28": [("reporting_platform", 1, "M"), ("grid_signal_interface", 1, "E"),
              ("bidirectional_metering", 2, "M"), ("data_logging", 2, "M")],
    "MC-29": [("dsm_override", 1, "M"), ("grid_signal_interface", 1, "E"), ("zonal_control", 2, "M"),
              ("data_logging", 3, "M"), ("predictive_control", 4, "M")],
    "MC-30": [("bms_integration", 1, "M"), ("digital_communication", 2, "M"), ("reporting_platform", 2, "E"),
              ("predictive_control", 3, "M"), ("weather_data", 3, "E"), ("occupancy_detection", 3, "E"),
              ("grid_signal_interface", 3, "E")],
}

# ─────────────────────────────────────────────────────────────────────────────
# Zaleznosci miedzydomenowe (funkcje wspolne dla wielu domen)
# ─────────────────────────────────────────────────────────────────────────────
CROSS_DOMAIN = [
    {"id": "occupancy", "factor_pl": "Obecnosc uzytkownikow", "capability": "occupancy_detection",
     "source_type": "official_methodology",
     "affected_domains": ["heating", "cooling", "ventilation", "lighting", "monitoring_and_control"],
     "description": "Jedna wiarygodna detekcja obecnosci steruje ogrzewaniem, chlodzeniem, wentylacja i oswietleniem."},
    {"id": "weather", "factor_pl": "Pogoda / prognoza", "capability": "weather_data",
     "source_type": "engineering_assumption",
     "affected_domains": ["heating", "cooling", "ventilation", "dynamic_building_envelope", "domestic_hot_water"],
     "description": "Dane pogodowe i prognoza wplywaja na ogrzewanie, chlodzenie, wentylacje, zacienienie i CWU."},
    {"id": "pv_storage", "factor_pl": "PV i magazyn energii", "capability": "self_consumption_optimization",
     "source_type": "official_methodology",
     "affected_domains": ["electricity", "electric_vehicle_charging", "heating", "cooling", "domestic_hot_water"],
     "description": "Lokalna produkcja i magazyn wplywaja na elektrycznosc, EV oraz elastycznosc HVAC/CWU (autokonsumpcja)."},
    {"id": "grid_signal", "factor_pl": "Sygnaly sieci / taryfy", "capability": "grid_signal_interface",
     "source_type": "official_methodology",
     "affected_domains": ["electricity", "electric_vehicle_charging", "heating", "cooling", "monitoring_and_control"],
     "description": "Sygnaly taryf/DSM/smart grid uruchamiaja elastycznosc w wielu domenach jednoczesnie."},
    {"id": "energy_data", "factor_pl": "Dane pomiarowe energii", "capability": "energy_metering",
     "source_type": "official_methodology",
     "affected_domains": ["heating", "cooling", "domestic_hot_water", "electricity", "monitoring_and_control"],
     "description": "Pomiar energii/ciepla/chlodu zasila raportowanie i FDD we wszystkich domenach oraz raport centralny."},
    {"id": "digital_integration", "factor_pl": "Integracja cyfrowa / BMS", "capability": "bms_integration",
     "source_type": "official_methodology",
     "affected_domains": ["heating", "cooling", "ventilation", "lighting", "dynamic_building_envelope", "monitoring_and_control"],
     "description": "Integracja cyfrowa i BMS warunkuje wyzsze poziomy sterowania i koordynacje miedzydomenowa (MC-30)."},
]
