# -*- coding: utf-8 -*-
"""Tresc ekspercka SRI — domena: Chlodzenie (Cooling). 10 uslug."""

EXPERT = {
    "C-1a": {
        "friendly_name": "Sterowanie chlodzeniem w pomieszczeniach",
        "purpose": "Dostarczanie chlodu do pomieszczen zgodnie z rzeczywistym zapotrzebowaniem i obecnoscia, utrzymujac komfort przy minimalnym zuzyciu energii.",
        "technical": "Regulacja mocy chlodniczej klimakonwektorow/belek/ukladow w oparciu o temperature zadana i rzeczywista strefy. Od termostatu centralnego, przez indywidualne sterowanie pomieszczen, po sterowanie komunikujace sie z BMS i detekcje obecnosci.",
        "energy_significance": "Chlodzenie jest energochlonne — indywidualna regulacja i wylaczanie chlodzenia w pustych strefach daja duze oszczednosci i redukcje szczytow mocy latem.",
        "level_notes": {
            0: "Brak automatyki — sterowanie reczne.",
            1: "Centralny termostat dla strefy/budynku.",
            2: "Indywidualna regulacja pomieszczen.",
            3: "Indywidualna regulacja z komunikacja miedzy sterownikami i z BMS.",
            4: "Jak poziom 3 plus detekcja obecnosci (chlodzenie tylko uzywanych pomieszczen).",
        },
        "technologies": ["KNX", "Loxone", "Modbus/BACnet", "sterowniki klimakonwektorow", "czujniki obecnosci"],
        "devices": ["klimakonwektory (fan-coil)", "belki chlodzace", "termostaty/sterowniki pomieszczeniowe", "czujniki temperatury i obecnosci"],
        "audit_verification": ["sprawdz niezalezne zadawanie temperatury chlodzenia per pomieszczenie", "ustal harmonogramy i integracje z BMS", "zweryfikuj detekcje obecnosci powiazana z chlodzeniem (poziom 4)"],
        "evidence": ["nastawy per pomieszczenie w BMS", "lista I/O", "schemat AKPiA", "zdjecia sterownikow fan-coil"],
        "common_mistakes": ["czujnik w niereprezentatywnym miejscu", "chlodzenie pustych stref", "brak martwej strefy miedzy grzaniem a chlodzeniem (patrz C-1f)"],
        "limitations": ["bezwladnosc ukladow plaszczyznowych (patrz C-1b)", "kondensacja przy zbyt niskiej temperaturze belek"],
        "dependencies": ["C-1c (temperatura wody lodowej)", "C-1f (blokada grzanie/chlodzenie)", "C-2a (zrodlo chlodu)", "DE-1 (zacienienie ogranicza zyski ciepla)"],
        "cross_domain_impact": ["ogrzewanie (unikanie jednoczesnej pracy)", "powloka budynku (zacienienie redukuje zapotrzebowanie)", "monitoring (optymalizacja wg obecnosci)"],
        "modernization": ["indywidualne sterowanie stref i harmonogramy", "detekcja obecnosci w salach", "integracja z zacienieniem i BMS"],
        "examples": ["biuro z fan-coilami sterowanymi per pokoj i detekcja obecnosci", "sala konferencyjna chlodzona tylko podczas rezerwacji"],
    },
    "C-1b": {
        "friendly_name": "Sterowanie chlodzeniem plaszczyznowym TABS",
        "purpose": "Regulacja chlodzenia w masie budynku (TABS) z wykorzystaniem bezwladnosci do stabilnego, energooszczednego chlodzenia (czesto pasywnego).",
        "technical": "Sterowanie ukladami TABS w trybie chlodzenia — glownie temperatura zasilania i harmonogramy z wyprzedzeniem, z ochrona przed kondensacja; wyzsze poziomy z predykcja.",
        "energy_significance": "Chlodzenie wysokotemperaturowe TABS umozliwia free-cooling i wysoka sprawnosc agregatow; przesuwanie chlodzenia na noc obniza koszty.",
        "level_notes": {
            0: "Brak automatyki chlodzenia TABS.",
            1: "Centralne sterowanie automatyczne.",
            2: "Sterowanie wg stref/warunkow z ochrona przed kondensacja.",
            3: "Sterowanie predykcyjne wykorzystujace bezwladnosc masy.",
        },
        "technologies": ["sterowanie temperatura zasilania", "ochrona antykondensacyjna (punkt rosy)", "predykcja pogody", "free-cooling"],
        "devices": ["zawory mieszajace z silownikami", "czujniki temperatury i wilgotnosci (punkt rosy)", "sterownik strefy TABS"],
        "audit_verification": ["ustal obecnosc TABS w trybie chlodzenia", "sprawdz ochrone przed kondensacja (pomiar wilgotnosci/punktu rosy)", "zweryfikuj sterowanie predykcyjne (poziom 3)"],
        "evidence": ["projekt TABS", "konfiguracja ochrony antykondensacyjnej", "trendy temperatur zasilania i wilgotnosci"],
        "common_mistakes": ["brak ochrony przed kondensacja (ryzyko zawilgocenia)", "zbyt niska temperatura zasilania", "jednoczesne grzanie i chlodzenie TABS"],
        "limitations": ["bardzo duza bezwladnosc", "ryzyko kondensacji przy wysokiej wilgotnosci", "wystepuje tylko przy TABS (triage vs C-1a)"],
        "dependencies": ["C-1c (temperatura wody)", "C-1f (blokada grzanie/chlodzenie)", "H-1b (ten sam TABS w trybie grzania)"],
        "cross_domain_impact": ["ogrzewanie (wspoldzielony uklad TABS)", "elastycznosc (magazyn chlodu w masie)"],
        "modernization": ["dodanie ochrony antykondensacyjnej", "sterowanie predykcyjne i free-cooling", "przesuniecie chlodzenia na noc"],
        "examples": ["biurowiec z chlodzonymi stropami i free-coolingiem nocnym", "budynek z TABS chlodzacym predykcyjnie wg prognozy"],
    },
    "C-1c": {
        "friendly_name": "Regulacja temperatury wody lodowej",
        "purpose": "Dostosowanie temperatury wody lodowej w sieci dystrybucji do rzeczywistego zapotrzebowania, zamiast produkcji nadmiernie zimnej wody.",
        "technical": "Regulacja temperatury zasilania/powrotu wody lodowej wg zapotrzebowania stref lub warunkow zewnetrznych (reset temperatury wody lodowej).",
        "energy_significance": "Podniesienie temperatury wody lodowej, gdy to mozliwe, znaczaco poprawia sprawnosc agregatow (EER) i umozliwia free-cooling.",
        "level_notes": {
            0: "Stala temperatura wody lodowej.",
            1: "Kompensacja wg warunkow zewnetrznych/harmonogramu.",
            2: "Reset temperatury wg rzeczywistego zapotrzebowania stref.",
        },
        "technologies": ["reset temperatury wody lodowej", "regulacja wg zapotrzebowania", "sterowniki agregatow/wezlow", "Modbus/BACnet"],
        "devices": ["czujniki temperatury zasilania/powrotu", "zawory mieszajace", "sterownik agregatu/BMS"],
        "audit_verification": ["sprawdz, czy temperatura wody lodowej jest stala czy resetowana", "zweryfikuj powiazanie z zapotrzebowaniem stref", "przejrzyj trendy temperatur"],
        "evidence": ["nastawy resetu temperatury", "trendy temperatur wody lodowej vs obciazenie", "schemat zrodla chlodu"],
        "common_mistakes": ["stala, zbyt niska temperatura 'na zapas'", "brak resetu mimo zmiennego obciazenia", "kolizja z wymaganiami osuszania"],
        "limitations": ["ograniczone wymaganiami osuszania/wilgotnosci", "zalezne od zrownowazenia hydraulicznego"],
        "dependencies": ["C-1d (pompy)", "C-2a/C-2b (zrodlo chlodu)", "C-1a (odbior w strefach)"],
        "cross_domain_impact": ["wentylacja (osuszanie vs temperatura wody)", "elektrycznosc (sprawnosc agregatow)"],
        "modernization": ["wdrozenie resetu temperatury wody lodowej", "podniesienie temperatury dla free-coolingu", "regulacja wg zapotrzebowania"],
        "examples": ["agregat z resetem temperatury wg obciazenia", "instalacja z podniesiona temperatura wody lodowej i free-coolingiem"],
    },
    "C-1d": {
        "friendly_name": "Sterowanie pompami obiegowymi chlodzenia",
        "purpose": "Redukcja energii pomp wody lodowej przez dopasowanie ich pracy do wymaganego przeplywu.",
        "technical": "Sterowanie pompami wody lodowej: od staloobrotowych, przez zmienna predkosc ze stalym cisnieniem, po regulacje wg zmiennego cisnienia/zapotrzebowania.",
        "energy_significance": "Pompy o zmiennej predkosci wg zapotrzebowania radykalnie obnizaja pomocnicze zuzycie energii chlodzenia.",
        "level_notes": {
            0: "Pompa staloobrotowa pracujaca ciagle.",
            1: "Zalaczanie/wylaczanie wg zapotrzebowania.",
            2: "Zmienna predkosc ze stala roznica cisnien.",
            3: "Zmienna predkosc ze zmienna (proporcjonalna) roznica cisnien.",
            4: "Regulacja wg rzeczywistego zapotrzebowania stref.",
        },
        "technologies": ["pompy elektroniczne (falownik)", "regulacja proporcjonalna", "sygnaly z zaworow", "Modbus/0-10V"],
        "devices": ["pompy wody lodowej z regulacja predkosci", "czujniki cisnienia/przeplywu", "sterownik/BMS"],
        "audit_verification": ["sprawdz typ pomp i tryb regulacji", "ustal, czy pompa reaguje na zapotrzebowanie", "przejrzyj trendy predkosci/mocy"],
        "evidence": ["DTR pomp", "nastawy trybu pracy", "trendy poboru mocy"],
        "common_mistakes": ["pompa w trybie stalej predkosci", "przewymiarowanie", "brak powiazania z zaworami stref"],
        "limitations": ["korzysc zalezy od zmiennosci obciazenia", "wymaga rownowazenia hydraulicznego"],
        "dependencies": ["C-1a (odbior w strefach)", "C-1c (temperatura wody)", "C-3 (raportowanie)"],
        "cross_domain_impact": ["elektrycznosc (redukcja poboru pomocniczego)"],
        "modernization": ["wymiana pomp na elektroniczne", "regulacja proporcjonalna/wg zapotrzebowania", "wylaczanie poza sezonem"],
        "examples": ["maszynownia chlodu z pompami elektronicznymi wg zapotrzebowania"],
    },
    "C-1f": {
        "friendly_name": "Blokada jednoczesnego grzania i chlodzenia",
        "purpose": "Zapobieganie marnotrawstwu energii przez uniemozliwienie jednoczesnego ogrzewania i chlodzenia tego samego pomieszczenia.",
        "technical": "Logika blokady (interlock) i martwej strefy (dead-band) miedzy trybami grzania i chlodzenia w strefie; wyzszy poziom z automatyczna koordynacja.",
        "energy_significance": "Eliminuje jeden z najczestszych i najbardziej kosztownych bledow — walke instalacji grzewczej z chlodnicza; szybki, tani zysk.",
        "level_notes": {
            0: "Brak blokady — mozliwe jednoczesne grzanie i chlodzenie.",
            1: "Martwa strefa/blokada uniemozliwiajaca jednoczesna prace.",
            2: "Automatyczna koordynacja trybow z optymalizacja przejsc.",
        },
        "technologies": ["logika interlock w sterowniku pomieszczenia", "dead-band grzanie/chlodzenie", "koordynacja w BMS"],
        "devices": ["sterownik pomieszczeniowy z trybem H/C", "czujnik temperatury", "BMS"],
        "audit_verification": ["sprawdz, czy istnieje martwa strefa miedzy nastawami H i C", "zweryfikuj, czy nie wystepuje jednoczesna praca (trendy)", "ustal koordynacje w BMS (poziom 2)"],
        "evidence": ["konfiguracja dead-band/interlock", "trendy trybow H/C strefy", "opis logiki w projekcie"],
        "common_mistakes": ["nakladajace sie nastawy grzania i chlodzenia", "brak koordynacji przy zmianie sezonu", "reczne wymuszenia obchodzace blokade"],
        "limitations": ["wymaga wspolnego sterownika/koordynacji trybow", "istotne zwlaszcza w strefach z H i C jednoczesnie"],
        "dependencies": ["H-1a/H-1b (grzanie strefy)", "C-1a/C-1b (chlodzenie strefy)"],
        "cross_domain_impact": ["ogrzewanie (bezposrednia koordynacja z chlodzeniem)"],
        "modernization": ["wprowadzenie martwej strefy i blokady", "koordynacja sezonowa w BMS", "usuniecie recznych wymuszen"],
        "examples": ["biuro z jedna nastawa komfortu i martwa strefa 2-3 K", "strefa z fan-coilem 4-rurowym i interlockiem H/C"],
    },
    "C-1g": {
        "friendly_name": "Sterowanie magazynem chlodu (TES)",
        "purpose": "Gromadzenie chlodu (woda lodowa/lod) w celu przesuniecia produkcji na godziny tanie/nocne i redukcji szczytow mocy.",
        "technical": "Sterowanie ladowaniem/rozladowaniem magazynu chlodu wg harmonogramu, zapotrzebowania i sygnalow zewnetrznych (taryfy, siec).",
        "energy_significance": "Produkcja chlodu noca (nizsza temperatura, tansza energia) i rozladunek w szczycie obniza koszty i zapotrzebowanie mocy oraz odciaza siec.",
        "level_notes": {
            0: "Brak magazynu chlodu lub brak sterowania.",
            1: "Sterowanie ladowaniem wg harmonogramu/temperatury.",
            2: "Optymalizacja wg zapotrzebowania i warunkow.",
            3: "Ladowanie sterowane sygnalami zewnetrznymi (taryfy/siec) — elastycznosc.",
        },
        "technologies": ["magazyny lodu/wody lodowej", "sterowanie taryfowe", "predykcja zapotrzebowania chlodu", "integracja z siecia"],
        "devices": ["zbiornik TES chlodu", "czujniki temperatury/naladowania", "zawory przelaczajace", "sterownik/EMS"],
        "audit_verification": ["ustal obecnosc i typ magazynu chlodu", "sprawdz logike ladowania/rozladowania", "zweryfikuj powiazanie z taryfami/siecia (poziom 3)"],
        "evidence": ["schemat z magazynem chlodu", "konfiguracja ladowania", "trendy naladowania vs ceny"],
        "common_mistakes": ["ladowanie w drogich godzinach", "zly dobor pojemnosci", "straty magazynu"],
        "limitations": ["straty postojowe", "miejsce i koszt inwestycji", "korzysc zalezy od profilu taryf/szczytow"],
        "dependencies": ["C-2a/C-2b (produkcja chlodu)", "C-4 (elastycznosc/siec)", "MC-25 (smart grid)"],
        "cross_domain_impact": ["elektrycznosc (redukcja szczytow mocy)", "elastycznosc energetyczna"],
        "modernization": ["dodanie magazynu chlodu do obiektow o duzym szczycie chlodniczym", "sterowanie taryfowe ladowania", "integracja z EMS"],
        "examples": ["centrum handlowe z magazynem lodu ladowanym noca", "biurowiec z TES rozladowywanym w szczycie letnim"],
    },
    "C-2a": {
        "friendly_name": "Sterowanie zrodlem chlodu (agregatem)",
        "purpose": "Optymalna praca agregatu chlodniczego tak, aby produkowal chlod o odpowiednich parametrach z wysoka sprawnoscia (EER).",
        "technical": "Sterowanie generatorem chlodu: od stalych parametrow, przez sterowanie zmienne wg obciazenia/warunkow, po optymalizacje punktu pracy i wspolprace z free-coolingiem.",
        "energy_significance": "Dostosowanie parametrow i unikanie taktowania podnosi EER; free-cooling i wyzsza temperatura wody lodowej daja duze oszczednosci.",
        "level_notes": {
            0: "Sterowanie staloparametrowe (on/off).",
            1: "Sterowanie zmienne wg obciazenia/warunkow zewnetrznych.",
            2: "Sterowanie wg zapotrzebowania z optymalizacja punktu pracy.",
            3: "Zaawansowana optymalizacja (EER, free-cooling, koordynacja).",
        },
        "technologies": ["agregaty inwerterowe", "free-cooling", "reset temperatury wody lodowej", "Modbus/BACnet"],
        "devices": ["agregat wody lodowej (chiller)", "czujniki temperatur i cisnien", "sterownik agregatu/BMS"],
        "audit_verification": ["ustal typ agregatu i logike sterowania", "sprawdz free-cooling i reset temperatury", "przejrzyj trendy EER/obciazenia"],
        "evidence": ["DTR agregatu", "nastawy sterownika", "trendy sprawnosci/obciazenia"],
        "common_mistakes": ["staly, nadmiarowy chlod", "brak free-coolingu mimo mozliwosci", "taktowanie przy niskim obciazeniu"],
        "limitations": ["sprawnosc zalezna od temperatury otoczenia", "ograniczenia zakresu modulacji"],
        "dependencies": ["C-1c (temperatura wody)", "C-2b (kaskada)", "C-3 (raportowanie)"],
        "cross_domain_impact": ["elektrycznosc (agregat to duzy odbiornik)", "elastycznosc (praca wg taryf)"],
        "modernization": ["wdrozenie free-coolingu", "reset temperatury wody lodowej", "wymiana na agregat inwerterowy"],
        "examples": ["chiller z free-coolingiem i resetem temperatury", "maszynownia z optymalizacja EER w BMS"],
    },
    "C-2b": {
        "friendly_name": "Kaskada / sekwencja zrodel chlodu",
        "purpose": "Optymalne zalaczanie kilku agregatow chlodniczych wg sprawnosci i obciazenia dla najnizszego zuzycia energii.",
        "technical": "Logika sekwencjonowania wielu agregatow wg sprawnosci czesciowej, obciazenia i kosztu, z rownowazeniem czasu pracy.",
        "energy_significance": "Praca agregatow w optymalnym zakresie obciazenia (unikanie pracy jednego mocno przy niskim EER) obniza zuzycie energii chlodzenia.",
        "level_notes": {
            0: "Brak koordynacji agregatow.",
            1: "Prosta sekwencja wg stalych priorytetow.",
            2: "Sekwencja wg obciazenia/sprawnosci.",
            3: "Sekwencja z kryterium kosztu/warunkow.",
            4: "Pelna optymalizacja predykcyjna z rownowazeniem pracy.",
        },
        "technologies": ["menedzer kaskady agregatow", "optymalizacja sprawnosci czesciowej", "predykcja zapotrzebowania"],
        "devices": ["sterownik nadrzedny", "liczniki energii agregatow", "czujniki temperatur/przeplywu"],
        "audit_verification": ["ustal liczbe agregatow i logike kaskady", "sprawdz kryteria przelaczania i rownowazenie motogodzin", "przejrzyj udzial agregatow w trendach"],
        "evidence": ["schemat maszynowni", "konfiguracja kaskady", "trendy udzialu agregatow"],
        "common_mistakes": ["staly priorytet ignorujacy EER czesciowy", "czeste przelaczanie", "praca jednego agregatu na skraju zakresu"],
        "limitations": ["wymaga opomiarowania agregatow", "zlozonosc przy wielu maszynach"],
        "dependencies": ["C-2a (agregaty)", "C-1g (magazyn chlodu)", "C-3 (raportowanie)"],
        "cross_domain_impact": ["elektrycznosc (redukcja poboru)", "elastycznosc energetyczna"],
        "modernization": ["menedzer kaskady wg sprawnosci czesciowej", "rownowazenie motogodzin", "integracja z magazynem chlodu"],
        "examples": ["maszynownia z 3 agregatami i kaskada wg EER czesciowego"],
    },
    "C-3": {
        "friendly_name": "Raportowanie pracy systemu chlodzenia",
        "purpose": "Dostarczanie danych o zuzyciu i sprawnosci chlodzenia dla monitoringu, wykrywania odchylen i optymalizacji.",
        "technical": "Zbieranie i prezentacja danych chlodzenia: zuzycie energii, chlod dostarczony, sprawnosc (EER), temperatury; wyzsze poziomy z benchmarkiem i alarmami.",
        "energy_significance": "Monitoring ujawnia spadki EER, wycieki i bledy nastaw; umozliwia utrzymanie sprawnosci i redukcje kosztow letnich.",
        "level_notes": {
            0: "Brak raportowania chlodzenia.",
            1: "Podstawowe informacje o stanie.",
            2: "Rejestracja zuzycia i historii.",
            3: "Analiza/benchmark i sygnalizacja odchylen.",
            4: "Pelne raportowanie sprawnosci ze wsparciem optymalizacji.",
        },
        "technologies": ["liczniki chlodu/energii", "historian/trendy", "dashboardy", "Modbus/BACnet"],
        "devices": ["cieplomierze chlodu", "liczniki energii agregatow", "czujniki temperatur", "koncentrator"],
        "audit_verification": ["sprawdz opomiarowanie chlodu i archiwizacje", "zweryfikuj dostepnosc trendow/raportow", "ustal alarmy odchylen (wyzsze poziomy)"],
        "evidence": ["dashboardy zuzycia chlodu", "eksport trendow EER", "lista opomiarowania"],
        "common_mistakes": ["brak licznikow chlodu", "dane bez analizy", "brak wskaznikow odniesienia"],
        "limitations": ["jakosc zalezy od opomiarowania", "koniecznosc kalibracji"],
        "dependencies": ["C-2a/C-2b (zrodla danych)", "MC-13 (centralne raportowanie)", "MC-4 (detekcja usterek)"],
        "cross_domain_impact": ["monitoring i sterowanie (dane do MC-13/MC-4)"],
        "modernization": ["montaz licznikow chlodu/energii", "dashboard EER i alarmy", "benchmarking kWh/m2 chlodu"],
        "examples": ["biurowiec z monitoringiem EER i alarmami spadku sprawnosci"],
    },
    "C-4": {
        "friendly_name": "Elastycznosc chlodzenia i wspolpraca z siecia",
        "purpose": "Przesuwanie poboru energii na chlodzenie w odpowiedzi na sygnaly sieci/taryf, redukcja szczytow i kosztow.",
        "technical": "Reakcja chlodzenia na sygnaly zewnetrzne (ceny, DSM, OZE) poprzez sterowanie agregatem, magazynem chlodu i masa budynku; od braku, przez taryfy, po automatyczna wspolprace z siecia.",
        "energy_significance": "Szczyt zapotrzebowania na moc czesto przypada na chlodzenie latem — elastycznosc obniza szczyty, koszty i wspiera siec; wysoka waga w SRI.",
        "level_notes": {
            0: "Brak reakcji na sygnaly zewnetrzne.",
            1: "Sterowanie wg statycznych taryf/harmonogramu.",
            2: "Reakcja na zmienne sygnaly cenowe/DSM.",
            3: "Automatyczna wspolpraca z siecia z magazynem chlodu i predykcja.",
            4: "Pelna, zoptymalizowana elastycznosc z rozliczaniem uslug sieciowych.",
        },
        "technologies": ["sterowanie taryfowe/cenowe", "OpenADR/DSM", "magazyn chlodu", "predykcja cen/pogody", "EMS"],
        "devices": ["EMS/sterownik elastycznosci", "magazyn chlodu (TES)", "licznik dwukierunkowy", "brama sygnalow"],
        "audit_verification": ["ustal reakcje chlodzenia na taryfy/sygnaly", "sprawdz wykorzystanie magazynu/masy", "zweryfikuj automatyzacje i rozliczenia DSM (wyzsze poziomy)"],
        "evidence": ["konfiguracja taryf/DSM w EMS", "trendy poboru vs ceny", "umowy uslug DSM"],
        "common_mistakes": ["brak magazynu ograniczajacy elastycznosc", "kolizja z komfortem", "deklaracja bez realnego sygnalu"],
        "limitations": ["wymaga magazynu/masy do przesuniec", "zalezy od dostepnosci sygnalow rynkowych"],
        "dependencies": ["C-1g (magazyn chlodu)", "C-2a (agregat)", "MC-25 (smart grid)", "E-3 (magazyn energii)"],
        "cross_domain_impact": ["elektrycznosc (redukcja szczytow)", "monitoring (MC-25/28/29 DSM)"],
        "modernization": ["sterowanie taryfowe agregatow", "dodanie magazynu chlodu", "integracja z EMS/sygnalami sieci"],
        "examples": ["centrum handlowe przesuwajace chlodzenie wg cen energii", "biurowiec z TES i reakcja na sygnaly DSM"],
    },
}
