# -*- coding: utf-8 -*-
"""Tresc ekspercka SRI — domena: Ciepla woda uzytkowa (DHW). 5 uslug."""

EXPERT = {
    "DHW-1a": {
        "friendly_name": "Sterowanie ladowaniem zasobnika CWU (grzalka / pompa ciepla)",
        "purpose": "Podgrzewanie zasobnika CWU z bezposredniego zrodla elektrycznego lub zintegrowanej pompy ciepla dokladnie wtedy, gdy jest to potrzebne i najtansze, z zachowaniem higieny.",
        "technical": "Regulacja ladowania zasobnika z grzalki elektrycznej lub wbudowanej pompy ciepla wg temperatury, harmonogramu i (na wyzszych poziomach) sygnalow zewnetrznych oraz nadwyzek PV.",
        "energy_significance": "CWU to znaczna czesc zuzycia energii; sterowanie czasem ladowania (taryfy, PV) i temperatura mocno obniza koszt bez utraty komfortu i bezpieczenstwa mikrobiologicznego.",
        "level_notes": {
            0: "Brak sterowania — ciagle utrzymywanie temperatury lub reczne zalaczanie.",
            1: "Sterowanie wg temperatury/harmonogramu.",
            2: "Optymalizacja ladowania wg zapotrzebowania i warunkow.",
            3: "Ladowanie sterowane sygnalami zewnetrznymi (taryfy/PV) z funkcja elastycznosci.",
        },
        "technologies": ["sterowanie taryfowe", "integracja z nadwyzka PV", "programy antylegionella", "SG-Ready dla PC"],
        "devices": ["zasobnik CWU z grzalka lub PC", "czujniki temperatury zasobnika", "sterownik/BMS", "licznik energii"],
        "audit_verification": ["ustal zrodlo ladowania (grzalka/PC)", "sprawdz harmonogram i logike temperatur", "zweryfikuj wykorzystanie taryf/PV i program antylegionella"],
        "evidence": ["nastawy sterownika CWU", "trendy temperatur zasobnika", "konfiguracja PV/taryf", "log programu antylegionella"],
        "common_mistakes": ["ciagle grzanie zasobnika 24/7", "ladowanie w godzinach szczytu", "pominiecie cyklu antylegionella"],
        "limitations": ["straty postojowe zasobnika", "kompromis komfort/higiena vs oszczednosci", "moc grzalki obciaza siec elektryczna"],
        "dependencies": ["DHW-2b (sekwencja zrodel)", "DHW-3 (raportowanie)", "E-4 (autokonsumpcja PV)", "H-2b (wspolna PC)"],
        "cross_domain_impact": ["elektrycznosc (grzalka/PC to duzy odbiornik — synergia z PV/magazynem)", "elastycznosc energetyczna"],
        "modernization": ["wprowadzenie ladowania wg taryf i nadwyzki PV", "obnizenie temperatury utrzymania z zachowaniem antylegionella", "wymiana na zasobnik z PC"],
        "examples": ["dom z zasobnikiem CWU ladowanym z nadwyzki PV", "budynek z grzalka sterowana taryfa nocna i cyklem antylegionella"],
    },
    "DHW-1b": {
        "friendly_name": "Sterowanie ladowaniem zasobnika CWU (z kotla/wezla)",
        "purpose": "Efektywne ladowanie zasobnika CWU z zrodla produkcji ciepla (kociol, wezel, PC hydrauliczna) przy zachowaniu komfortu i higieny.",
        "technical": "Regulacja ladowania zasobnika CWU zasilanego z generatora ciepla — sterowanie temperatura, priorytetem CWU wzgledem ogrzewania i harmonogramem; wyzsze poziomy wg zapotrzebowania i sygnalow.",
        "energy_significance": "Priorytetyzacja i wlasciwe temperatury ladowania ograniczaja straty i pozwalaja zrodlu pracowac sprawnie; sterowanie czasem obniza koszty.",
        "level_notes": {
            0: "Brak sterowania — stale utrzymywanie temperatury.",
            1: "Sterowanie wg temperatury/harmonogramu z priorytetem CWU.",
            2: "Optymalizacja wg zapotrzebowania i warunkow pracy zrodla.",
            3: "Ladowanie sterowane sygnalami zewnetrznymi (taryfy/OZE) — elastycznosc.",
        },
        "technologies": ["priorytet CWU w sterowniku zrodla", "zawory przelaczajace CWU/CO", "sterowanie taryfowe", "programy antylegionella"],
        "devices": ["zasobnik CWU", "zawor przelaczajacy (priorytet)", "czujniki temperatury zasobnika", "sterownik zrodla/BMS"],
        "audit_verification": ["sprawdz logike priorytetu CWU wzgledem ogrzewania", "ustal harmonogram i temperatury ladowania", "zweryfikuj antylegionella i sterowanie taryfami (wyzsze poziomy)"],
        "evidence": ["schemat hydrauliczny z priorytetem CWU", "nastawy sterownika", "trendy temperatur"],
        "common_mistakes": ["brak priorytetu CWU (dlugie ladowanie kosztem CO)", "za wysoka temperatura ladowania", "grzanie w szczycie"],
        "limitations": ["straty postojowe zasobnika", "wspoldzielenie zrodla z ogrzewaniem", "bezwladnosc ladowania"],
        "dependencies": ["H-2a/H-2b (zrodlo)", "DHW-2b (sekwencja zrodel)", "DHW-3 (raportowanie)"],
        "cross_domain_impact": ["ogrzewanie (wspoldzielone zrodlo i sterowanie priorytetem)"],
        "modernization": ["wdrozenie priorytetu CWU i harmonogramow", "sterowanie ladowaniem wg taryf", "izolacja zasobnika i obiegow"],
        "examples": ["kotlownia z zasobnikiem CWU i priorytetem cieplej wody", "wezel cieplny z ladowaniem CWU wg harmonogramu"],
    },
    "DHW-1d": {
        "friendly_name": "Sterowanie CWU z kolektorem slonecznym i dogrzewaniem",
        "purpose": "Maksymalne wykorzystanie ciepla ze slonca do przygotowania CWU, z inteligentnym dogrzewaniem tylko wtedy, gdy energia sloneczna nie wystarcza.",
        "technical": "Sterowanie ukladem solarnym (kolektory) z zasobnikiem i zrodlem dogrzewajacym — priorytet dla energii solarnej, sterowanie pompa solarna i logika dogrzewania wg prognozy/uzytkowania.",
        "energy_significance": "Priorytet solarny minimalizuje uzycie zrodla konwencjonalnego; inteligentne dogrzewanie unika niepotrzebnego grzania, gdy zapowiada sie naslonecznienie.",
        "level_notes": {
            0: "Brak sterowania koordynujacego solar i dogrzewanie.",
            1: "Podstawowe sterowanie pompa solarna wg roznicy temperatur.",
            2: "Koordynacja solar + dogrzewanie wg zapotrzebowania.",
            3: "Optymalizacja z prognoza naslonecznienia/uzycia — minimalizacja dogrzewania.",
        },
        "technologies": ["regulator solarny roznicowy", "prognoza naslonecznienia", "logika priorytetu solarnego", "sterowanie dogrzewaniem"],
        "devices": ["kolektory sloneczne", "pompa solarna", "czujniki temperatury kolektora i zasobnika", "zasobnik biwalentny", "sterownik solarny"],
        "audit_verification": ["ustal obecnosc kolektorow i logike pompy solarnej", "sprawdz priorytet solarny wzgledem dogrzewania", "zweryfikuj wykorzystanie prognozy (poziom 3)"],
        "evidence": ["schemat instalacji solarnej", "nastawy regulatora solarnego", "trendy uzysku solarnego"],
        "common_mistakes": ["dogrzewanie zasobnika rano mimo zapowiadanego slonca", "zle rozmieszczone czujniki w zasobniku biwalentnym", "brak ochrony przed przegrzewem/stagnacja"],
        "limitations": ["zaleznosc od pogody", "wymagany zasobnik biwalentny", "sezonowa zmiennosc uzysku"],
        "dependencies": ["DHW-1b (dogrzewanie z kotla)", "DHW-2b (sekwencja)", "DHW-3 (raportowanie uzysku)"],
        "cross_domain_impact": ["elektrycznosc/OZE (komplementarnosc z PV)", "ogrzewanie (wspolne zrodlo dogrzewania)"],
        "modernization": ["dodanie prognozowego sterowania dogrzewaniem", "optymalizacja rozmieszczenia czujnikow", "integracja z BMS i raportowaniem uzysku"],
        "examples": ["dom z kolektorami i zasobnikiem biwalentnym ze sterowaniem prognozowym", "hotel z instalacja solarna CWU i dogrzewaniem gazowym"],
    },
    "DHW-2b": {
        "friendly_name": "Kaskada / sekwencja zrodel CWU",
        "purpose": "Optymalny dobor i kolejnosc zrodel przygotowania CWU (np. PC + grzalka + kolektor) dla najnizszego kosztu i wysokiej sprawnosci.",
        "technical": "Logika sekwencjonowania kilku generatorow CWU wg sprawnosci, kosztu i dostepnosci OZE, z rownowazeniem czasu pracy i priorytetem zrodel taniej energii.",
        "energy_significance": "Wlasciwa kolejnosc zrodel (najpierw solar/PC, potem szczytowe) maksymalizuje udzial taniej energii i obniza koszt CWU.",
        "level_notes": {
            0: "Brak koordynacji zrodel CWU.",
            1: "Prosta sekwencja wg stalych priorytetow.",
            2: "Sekwencja wg obciazenia/sprawnosci.",
            3: "Sekwencja z kryterium kosztu/warunkow.",
            4: "Pelna optymalizacja predykcyjna z rownowazeniem pracy.",
        },
        "technologies": ["menedzer zrodel CWU w BMS", "optymalizacja kosztowa", "integracja solar/PC/grzalka"],
        "devices": ["sterownik nadrzedny CWU", "liczniki energii zrodel", "zawory przelaczajace", "czujniki temperatur"],
        "audit_verification": ["ustal liczbe/typy zrodel CWU", "sprawdz logike priorytetow i warunki przelaczania", "zweryfikuj kryteria kosztowe i rownowazenie (wyzsze poziomy)"],
        "evidence": ["schemat zrodel CWU", "konfiguracja priorytetow", "trendy udzialu zrodel"],
        "common_mistakes": ["staly priorytet ignorujacy koszt", "czeste przelaczanie zrodel", "grzalka jako pierwsze zrodlo zamiast ostatniego"],
        "limitations": ["wymaga opomiarowania zrodel", "zlozonosc przy wielu generatorach"],
        "dependencies": ["DHW-1a/DHW-1b/DHW-1d (poszczegolne zrodla)", "DHW-3 (raportowanie)"],
        "cross_domain_impact": ["elektrycznosc (priorytet PC/PV nad grzalka)", "elastycznosc energetyczna"],
        "modernization": ["wdrozenie menedzera zrodel z kryterium kosztu", "priorytet OZE/PC przed grzalka", "rownowazenie motogodzin"],
        "examples": ["uklad CWU: kolektor + PC + grzalka szczytowa z kaskada kosztowa", "hotel z kilkoma podgrzewaczami i sekwencja wg sprawnosci"],
    },
    "DHW-3": {
        "friendly_name": "Raportowanie pracy systemu CWU",
        "purpose": "Dostarczanie danych o zuzyciu i sprawnosci przygotowania CWU dla monitoringu, wykrywania strat (np. cyrkulacji) i optymalizacji.",
        "technical": "Zbieranie i prezentacja danych CWU: zuzycie energii/wody, temperatury, uzysk solarny, straty cyrkulacji; wyzsze poziomy z benchmarkiem i alarmami.",
        "energy_significance": "Ujawnia ukryte straty (np. przewymiarowana cyrkulacja, przegrzewanie) i umozliwia korekte nastaw — czesto szybkie, bezkosztowe oszczednosci.",
        "level_notes": {
            0: "Brak raportowania CWU.",
            1: "Podstawowe informacje o stanie (temperatury).",
            2: "Rejestracja zuzycia i historii.",
            3: "Analiza/benchmark i sygnalizacja odchylen.",
            4: "Pelne raportowanie ze sprawnoscia i wsparciem optymalizacji.",
        },
        "technologies": ["liczniki ciepla/wody", "historian/trendy", "dashboardy", "M-Bus/Modbus"],
        "devices": ["cieplomierze/wodomierze", "czujniki temperatur (zasobnik, cyrkulacja)", "koncentrator danych"],
        "audit_verification": ["sprawdz opomiarowanie CWU i archiwizacje danych", "zweryfikuj dostepnosc trendow/raportow", "ustal alarmy odchylen (wyzsze poziomy)"],
        "evidence": ["dashboardy zuzycia CWU", "eksport trendow", "lista opomiarowania"],
        "common_mistakes": ["brak licznikow (szacunki)", "ignorowanie strat cyrkulacji", "brak wskaznikow odniesienia"],
        "limitations": ["jakosc zalezy od opomiarowania", "koniecznosc utrzymania/kalibracji"],
        "dependencies": ["DHW-1a/DHW-1b/DHW-1d (zrodla danych)", "MC-13 (centralne raportowanie)", "MC-4 (detekcja usterek)"],
        "cross_domain_impact": ["monitoring i sterowanie (dane do MC-13/MC-4)", "gospodarka woda"],
        "modernization": ["montaz cieplomierzy/wodomierzy CWU", "monitoring strat cyrkulacji", "dashboard i alarmy odchylen"],
        "examples": ["hotel z monitoringiem zuzycia CWU i strat cyrkulacji", "budynek z dashboardem uzysku solarnego CWU"],
    },
}
