# -*- coding: utf-8 -*-
"""Tresc ekspercka SRI — domena: Elektrycznosc (Electricity). 7 uslug."""

EXPERT = {
    "E-2": {
        "friendly_name": "Raportowanie produkcji energii (PV/OZE)",
        "purpose": "Monitorowanie i prezentacja produkcji energii z lokalnych zrodel (np. PV), aby ocenic uzysk, wykrywac usterki i optymalizowac autokonsumpcje.",
        "technical": "Zbieranie i prezentacja danych produkcji lokalnej: moc/energia chwilowa i skumulowana, uzysk per string/falownik; wyzsze poziomy z benchmarkiem, alarmami i prognoza.",
        "energy_significance": "Bez pomiaru produkcji nie da sie zarzadzac autokonsumpcja ani wykryc spadku uzysku (zabrudzenia, awarie) — podstawa optymalizacji OZE.",
        "level_notes": {
            0: "Brak raportowania produkcji.",
            1: "Podstawowe wskazanie biezacej produkcji.",
            2: "Rejestracja i historia produkcji.",
            3: "Analiza/benchmark uzysku i alarmy odchylen.",
            4: "Pelne raportowanie z prognoza i wsparciem optymalizacji.",
        },
        "technologies": ["monitoring falownikow", "liczniki produkcji", "dashboardy PV", "prognoza produkcji", "Modbus/API falownikow"],
        "devices": ["falowniki PV", "liczniki energii produkcji", "czujniki naslonecznienia", "brama monitoringu"],
        "audit_verification": ["sprawdz monitoring falownikow i archiwizacje produkcji", "zweryfikuj dostepnosc trendow/uzysku", "ustal alarmy odchylen i prognoze (wyzsze poziomy)"],
        "evidence": ["dashboard produkcji PV", "eksport uzysku dziennego/miesiecznego", "konfiguracja monitoringu falownikow"],
        "common_mistakes": ["brak monitoringu per string (niewykryte awarie)", "dane bez alarmow spadku uzysku", "brak porownania z prognoza/benchmarkiem"],
        "limitations": ["jakosc zalezy od monitoringu falownikow", "zaleznosc uzysku od pogody"],
        "dependencies": ["E-4 (autokonsumpcja)", "E-3 (magazyn)", "E-12 (zuzycie)", "MC-13 (centralne raportowanie)"],
        "cross_domain_impact": ["ogrzewanie/CWU/chlodzenie (sterowanie wg nadwyzki PV)", "elastycznosc energetyczna"],
        "modernization": ["wdrozenie monitoringu per string", "dashboard i alarmy uzysku", "integracja prognozy produkcji"],
        "examples": ["biurowiec z monitoringiem PV per falownik i alarmami spadku uzysku"],
    },
    "E-3": {
        "friendly_name": "Magazynowanie energii elektrycznej",
        "purpose": "Gromadzenie lokalnie wytworzonej energii (np. z PV) w magazynie, aby zwiekszyc autokonsumpcje, obnizyc szczyty i wspierac siec.",
        "technical": "Sterowanie magazynem energii (bateria): ladowanie/rozladowanie wg autokonsumpcji, taryf, szczytow i sygnalow sieci; wyzsze poziomy z pelna optymalizacja i uslugami sieciowymi.",
        "energy_significance": "Magazyn zwieksza autokonsumpcje PV, redukuje szczyty mocy i koszty; kluczowy dla elastycznosci energetycznej (wysoka waga w SRI).",
        "level_notes": {
            0: "Brak magazynu lub brak sterowania.",
            1: "Podstawowe sterowanie ladowaniem/rozladowaniem (autokonsumpcja).",
            2: "Optymalizacja wg taryf/szczytow i autokonsumpcji.",
            3: "Sterowanie z uslugami sieciowymi (peak shaving, wsparcie sieci).",
            4: "Pelna optymalizacja z dwukierunkowa wspolpraca i rozliczaniem uslug.",
        },
        "technologies": ["magazyny bateryjne (BESS)", "EMS", "peak shaving", "integracja z siecia (V2G/uslugi)", "Modbus/API"],
        "devices": ["bateria/magazyn energii", "falownik hybrydowy/magazynu", "licznik dwukierunkowy", "EMS"],
        "audit_verification": ["ustal obecnosc i pojemnosc magazynu", "sprawdz logike ladowania/rozladowania (autokonsumpcja/taryfy/szczyty)", "zweryfikuj uslugi sieciowe (wyzsze poziomy)"],
        "evidence": ["DTR magazynu/falownika", "konfiguracja EMS", "trendy naladowania vs produkcja/ceny"],
        "common_mistakes": ["magazyn tylko na autokonsumpcje bez peak shaving", "zle dobrana pojemnosc", "brak koordynacji z PV/odbiorami"],
        "limitations": ["koszt i zywotnosc baterii", "korzysc zalezy od profilu produkcji/zuzycia i taryf"],
        "dependencies": ["E-2 (produkcja)", "E-4 (autokonsumpcja)", "E-11 (raportowanie magazynu)", "MC-25 (smart grid)"],
        "cross_domain_impact": ["ogrzewanie/chlodzenie (magazyn energii komplementarny do magazynow ciepla/chlodu)", "EV (wspolna elastycznosc)"],
        "modernization": ["dodanie magazynu do instalacji PV", "wdrozenie peak shaving w EMS", "integracja z uslugami sieciowymi"],
        "examples": ["obiekt z PV + magazyn i peak shaving w szczycie", "budynek z EMS optymalizujacym baterie wg taryf"],
    },
    "E-4": {
        "friendly_name": "Optymalizacja autokonsumpcji energii z PV",
        "purpose": "Maksymalne zuzycie na miejscu energii wyprodukowanej lokalnie (PV), przez sterowanie odbiornikami zgodnie z biezaca produkcja.",
        "technical": "Koordynacja odbiornikow (CWU, PC, chlodzenie, EV, magazyn) z produkcja PV — od braku, przez proste sterowanie nadwyzka, po predykcyjna optymalizacje autokonsumpcji.",
        "energy_significance": "Autokonsumpcja jest zwykle bardziej oplacalna niz oddawanie do sieci — inteligentne sterowanie odbiornikami znaczaco podnosi jej udzial.",
        "level_notes": {
            0: "Brak optymalizacji autokonsumpcji.",
            1: "Proste sterowanie odbiornikami wg nadwyzki produkcji.",
            2: "Koordynacja wielu odbiornikow wg produkcji i priorytetow.",
            3: "Predykcyjna optymalizacja autokonsumpcji (prognoza produkcji/zuzycia).",
        },
        "technologies": ["EMS/HEMS", "sterowanie odbiornikami wg nadwyzki", "prognoza PV/zuzycia", "integracja PC/CWU/EV/magazyn"],
        "devices": ["EMS", "licznik dwukierunkowy", "przekazniki/sterowniki odbiornikow", "falownik PV"],
        "audit_verification": ["sprawdz, czy odbiorniki reaguja na nadwyzke PV", "ustal priorytety i koordynacje odbiornikow", "zweryfikuj optymalizacje predykcyjna (poziom 3)"],
        "evidence": ["konfiguracja EMS/priorytetow", "trendy autokonsumpcji", "logi sterowania odbiornikami wg PV"],
        "common_mistakes": ["oddawanie nadwyzki do sieci mimo dostepnych odbiornikow", "brak priorytetow (konflikty odbiornikow)", "brak prognozy (nieoptymalne decyzje)"],
        "limitations": ["wymaga sterowalnych odbiornikow", "korzysc zalezy od zbieznosci produkcji i zuzycia"],
        "dependencies": ["E-2 (produkcja)", "E-3 (magazyn)", "H-2b/DHW-1a (odbiorniki PC/CWU)", "EV-15/EV-16 (ladowanie EV)"],
        "cross_domain_impact": ["ogrzewanie/CWU/chlodzenie/EV (sterowane wg nadwyzki PV)", "elastycznosc energetyczna"],
        "modernization": ["wdrozenie EMS koordynujacego odbiorniki wg PV", "priorytetyzacja CWU/PC/EV/magazyn", "prognozowa optymalizacja"],
        "examples": ["dom z HEMS grzejacym CWU i ladujacym EV z nadwyzki PV", "obiekt z priorytetem autokonsumpcji przed oddaniem do sieci"],
    },
    "E-5": {
        "friendly_name": "Sterowanie kogeneracja (CHP)",
        "purpose": "Optymalna praca ukladu skojarzonego (produkcja pradu i ciepla) tak, aby maksymalizowac korzysc z jednoczesnej produkcji energii i ciepla.",
        "technical": "Sterowanie CHP wg zapotrzebowania na cieplo/energie, cen i sygnalow sieci — od podstawowego, po sterowanie zoptymalizowane wg warunkow rynkowych.",
        "energy_significance": "CHP jest najbardziej oplacalny przy jednoczesnym wykorzystaniu ciepla i pradu; inteligentne sterowanie dopasowuje prace do zapotrzebowania i cen.",
        "level_notes": {
            0: "Brak sterowania optymalizujacego CHP.",
            1: "Sterowanie wg zapotrzebowania na cieplo lub energie.",
            2: "Sterowanie zoptymalizowane wg warunkow (ceny, siec, zapotrzebowanie).",
        },
        "technologies": ["sterowniki CHP", "praca wg zapotrzebowania cieplnego/elektrycznego", "optymalizacja kosztowa", "integracja z buforem"],
        "devices": ["agregat kogeneracyjny", "bufor ciepla", "liczniki energii/ciepla", "sterownik/EMS"],
        "audit_verification": ["ustal obecnosc CHP i logike sterowania (cieplo/energia)", "sprawdz wspolprace z buforem", "zweryfikuj optymalizacje wg cen/sieci (poziom 2)"],
        "evidence": ["DTR CHP", "konfiguracja sterowania", "trendy produkcji ciepla/energii vs zapotrzebowanie"],
        "common_mistakes": ["praca CHP bez odbioru ciepla (marnowanie)", "brak bufora (taktowanie)", "ignorowanie cen energii"],
        "limitations": ["oplacalnosc zalezy od jednoczesnego zapotrzebowania cieplo/prad", "wystepuje tylko przy instalacji CHP"],
        "dependencies": ["H-1f (bufor)", "H-2d (kaskada zrodel)", "E-8 (praca w microgrid)", "E-2 (raportowanie produkcji)"],
        "cross_domain_impact": ["ogrzewanie (CHP jako zrodlo ciepla)", "elastycznosc energetyczna"],
        "modernization": ["sterowanie CHP wg zapotrzebowania cieplnego i cen", "dodanie bufora", "integracja z EMS/microgrid"],
        "examples": ["szpital z CHP sterowanym wg zapotrzebowania na cieplo i energie"],
    },
    "E-8": {
        "friendly_name": "Wsparcie pracy (mikro)sieci",
        "purpose": "Umozliwienie budynkowi pracy w roznych trybach sieci (np. wyspowym), wspierajac lokalna mikrosiec i ciaglosc zasilania.",
        "technical": "Sterowanie umozliwiajace prace w trybach on-grid/off-grid (wyspa), koordynacja zrodel, magazynu i odbiorow; wyzsze poziomy z automatycznym przelaczaniem i optymalizacja.",
        "energy_significance": "Wspiera integracje OZE i odpornosc (rezyliencje) zasilania; umozliwia lokalny bilans energii i uslugi dla sieci.",
        "level_notes": {
            0: "Brak wsparcia trybow (mikro)sieci.",
            1: "Podstawowe wsparcie/przelaczanie trybow.",
            2: "Koordynacja zrodel i magazynu w trybach sieci.",
            3: "Automatyczna praca wyspowa z optymalizacja i bezprzerwowym przelaczaniem.",
        },
        "technologies": ["falowniki gridformujace", "sterowanie microgrid", "automatyczne przelaczanie SZR", "EMS"],
        "devices": ["falowniki hybrydowe/gridformujace", "magazyn energii", "uklad SZR/rozlaczniki", "kontroler microgrid/EMS"],
        "audit_verification": ["ustal zdolnosc pracy wyspowej i tryby sieci", "sprawdz koordynacje zrodel/magazynu", "zweryfikuj automatyczne przelaczanie (wyzsze poziomy)"],
        "evidence": ["schemat microgrid/SZR", "konfiguracja kontrolera", "testy przelaczania trybow"],
        "common_mistakes": ["magazyn/falownik bez funkcji gridformujacej", "brak testow przelaczania", "niezbilansowane zrodla w trybie wyspy"],
        "limitations": ["wymaga odpowiednich falownikow/architektury", "zlozonosc i koszt", "aspekty formalne przylaczenia"],
        "dependencies": ["E-3 (magazyn)", "E-5 (CHP)", "E-2 (produkcja)", "MC-25 (smart grid)"],
        "cross_domain_impact": ["elastycznosc energetyczna", "cala infrastruktura (rezyliencja zasilania TBS)"],
        "modernization": ["wdrozenie falownikow gridformujacych i EMS microgrid", "automatyczne przelaczanie na wyspe", "koordynacja zrodel/magazynu"],
        "examples": ["obiekt krytyczny z praca wyspowa PV+magazyn+CHP", "kampus z lokalna mikrosiecia"],
    },
    "E-11": {
        "friendly_name": "Raportowanie pracy magazynu energii",
        "purpose": "Dostarczanie danych o pracy magazynu energii (naladowanie, cykle, sprawnosc), aby monitorowac stan, kondycje i efekty ekonomiczne.",
        "technical": "Zbieranie i prezentacja danych magazynu: SoC, cykle, sprawnosc round-trip, degradacja; wyzsze poziomy z benchmarkiem, alarmami i wsparciem optymalizacji.",
        "energy_significance": "Monitoring magazynu pozwala ocenic realne korzysci, kondycje baterii i skutecznosc strategii ladowania — warunek optymalizacji.",
        "level_notes": {
            0: "Brak raportowania magazynu.",
            1: "Podstawowe wskazanie stanu (SoC).",
            2: "Rejestracja i historia pracy magazynu.",
            3: "Analiza/benchmark i alarmy (degradacja, odchylenia).",
            4: "Pelne raportowanie ze sprawnoscia i wsparciem optymalizacji.",
        },
        "technologies": ["monitoring BMS baterii", "historian/trendy", "dashboardy magazynu", "analiza degradacji"],
        "devices": ["magazyn energii z BMS", "licznik energii", "brama monitoringu/EMS"],
        "audit_verification": ["sprawdz monitoring SoC/cykli i archiwizacje", "zweryfikuj wskazniki sprawnosci/degradacji", "ustal alarmy (wyzsze poziomy)"],
        "evidence": ["dashboard magazynu", "trendy SoC/cykli", "raport sprawnosci round-trip"],
        "common_mistakes": ["brak monitoringu degradacji", "dane bez analizy oplacalnosci", "brak alarmow o awariach ogniw"],
        "limitations": ["jakosc zalezy od danych z BMS baterii", "wymaga interpretacji"],
        "dependencies": ["E-3 (magazyn)", "E-12 (zuzycie)", "MC-13 (centralne raportowanie)"],
        "cross_domain_impact": ["monitoring i sterowanie (dane do MC-13)", "elastycznosc energetyczna"],
        "modernization": ["wdrozenie dashboardu magazynu", "monitoring degradacji i alarmy", "raporty oplacalnosci"],
        "examples": ["obiekt z dashboardem magazynu (SoC, cykle, sprawnosc)"],
    },
    "E-12": {
        "friendly_name": "Raportowanie zuzycia energii elektrycznej",
        "purpose": "Pomiar i prezentacja zuzycia energii elektrycznej (najlepiej z podzialem na obwody/odbiory), aby zarzadzac energia i wykrywac marnotrawstwo.",
        "technical": "Zbieranie i prezentacja danych zuzycia: sumaryczne i podlicznikowe (submetering), profile mocy, szczyty; wyzsze poziomy z benchmarkiem, alarmami i wsparciem optymalizacji.",
        "energy_significance": "Podlicznikowanie ujawnia najwiekszych odbiorcow i marnotrawstwo (np. praca poza godzinami), umozliwiajac celowane oszczednosci i zarzadzanie szczytami.",
        "level_notes": {
            0: "Brak raportowania zuzycia.",
            1: "Pomiar zuzycia sumarycznego.",
            2: "Rejestracja i historia zuzycia (profile).",
            3: "Submetering/benchmark i alarmy odchylen.",
            4: "Pelne raportowanie z analiza i wsparciem optymalizacji.",
        },
        "technologies": ["submetering (podliczniki)", "analiza profili obciazenia", "dashboardy energetyczne", "Modbus/M-Bus"],
        "devices": ["liczniki/analizatory energii", "przekladniki pradowe", "brama/koncentrator", "system monitoringu energii"],
        "audit_verification": ["sprawdz zakres opomiarowania (sumaryczne vs podliczniki)", "zweryfikuj dostepnosc profili/historii", "ustal alarmy odchylen (wyzsze poziomy)"],
        "evidence": ["dashboard zuzycia energii", "schemat opomiarowania obwodow", "eksport profili mocy"],
        "common_mistakes": ["tylko licznik glowny (brak submeteringu)", "dane bez analizy", "brak identyfikacji szczytow/baseloadu"],
        "limitations": ["koszt rozbudowanego submeteringu", "koniecznosc utrzymania systemu"],
        "dependencies": ["E-2 (produkcja)", "E-11 (magazyn)", "MC-13 (centralne raportowanie)", "MC-4 (detekcja usterek)"],
        "cross_domain_impact": ["wszystkie domeny (identyfikacja odbiorcow: HVAC, oswietlenie, IT)", "elastycznosc (zarzadzanie szczytami)"],
        "modernization": ["wdrozenie submeteringu kluczowych obwodow", "dashboard i alarmy odchylen", "analiza baseloadu i szczytow"],
        "examples": ["biurowiec z submeteringiem HVAC/oswietlenia/IT i dashboardem", "obiekt z alarmami zuzycia poza godzinami pracy"],
    },
}
