# -*- coding: utf-8 -*-
"""Tresc ekspercka SRI — domena: Dynamiczna powloka budynku (Dynamic building envelope). 3 uslugi."""

EXPERT = {
    "DE-1": {
        "friendly_name": "Sterowanie zacienieniem / roletami",
        "purpose": "Automatyczne sterowanie oslonami przeciwslonecznymi (rolety, zaluzje, markizy), aby ograniczac zyski ciepla latem, wykorzystywac je zima i chronic przed olsnieniem.",
        "technical": "Sterowanie oslonami wg naslonecznienia, pozycji slonca, temperatury i obecnosci — od recznego, przez czasowe/nasloneczniowe, po sterowanie zoptymalizowane wg pozycji slonca i potrzeb HVAC/oswietlenia.",
        "energy_significance": "Zacienienie redukuje szczyty chlodnicze latem i zyski ciepla, a zima pozwala na darmowe zyski sloneczne; wplywa tez na zapotrzebowanie na oswietlenie.",
        "level_notes": {
            0: "Sterowanie reczne oslonami.",
            1: "Sterowanie automatyczne (czasowe lub wg naslonecznienia).",
            2: "Sterowanie wg naslonecznienia i temperatury z uwzglednieniem stref.",
            3: "Sterowanie wg pozycji slonca z ochrona przed olsnieniem.",
            4: "Zoptymalizowane sterowanie zintegrowane z HVAC i oswietleniem (predykcja).",
        },
        "technologies": ["stacja pogodowa/czujniki naslonecznienia", "sledzenie pozycji slonca", "KNX/Loxone", "integracja z HVAC i oswietleniem"],
        "devices": ["napedy rolet/zaluzji", "czujniki naslonecznienia i wiatru", "stacja pogodowa", "sterowniki zacienienia"],
        "audit_verification": ["sprawdz automatyzacje oslon i czujniki naslonecznienia", "ustal logike wg pozycji slonca/temperatury", "zweryfikuj integracje z HVAC/oswietleniem (poziom 4)"],
        "evidence": ["schemat sterowania oslonami", "nastawy logiki naslonecznienia", "trendy pozycji oslon vs naslonecznienie"],
        "common_mistakes": ["brak ochrony przed wiatrem (uszkodzenia)", "konflikt z daylight harvesting (za duzo zaciemnienia)", "sterowanie tylko czasowe bez czujnikow"],
        "limitations": ["wymaga napedow i czujnikow zewnetrznych", "kompromis miedzy zacienieniem a swiatlem dziennym/widokiem"],
        "dependencies": ["L-2 (swiatlo dzienne)", "DE-2 (okna/HVAC)", "C-1a (redukcja zyskow ciepla)"],
        "cross_domain_impact": ["chlodzenie (redukcja szczytow letnich)", "ogrzewanie (zyski sloneczne zima)", "oswietlenie (swiatlo dzienne)"],
        "modernization": ["automatyzacja rolet z czujnikami naslonecznienia/wiatru", "sterowanie wg pozycji slonca", "koordynacja z oswietleniem i HVAC"],
        "examples": ["biurowiec z fasada z automatycznymi zaluzjami wg pozycji slonca", "dom z roletami sterowanymi naslonecznieniem i wiatrem"],
    },
    "DE-2": {
        "friendly_name": "Sterowanie otwieraniem okien z HVAC",
        "purpose": "Koordynacja otwierania/zamykania okien z praca ogrzewania, chlodzenia i wentylacji, aby umozliwic przewietrzanie bez marnowania energii.",
        "technical": "Sterowanie okien (lub sygnalizacja ich stanu) zintegrowane z HVAC — blokada grzania/chlodzenia przy otwartym oknie, sterowane przewietrzanie naturalne; wyzsze poziomy z automatyka i optymalizacja.",
        "energy_significance": "Blokowanie HVAC przy otwartych oknach eliminuje typowe marnotrawstwo; sterowane przewietrzanie umozliwia darmowe chlodzenie nocne.",
        "level_notes": {
            0: "Brak koordynacji okien z HVAC.",
            1: "Detekcja otwarcia okna z blokada grzania/chlodzenia strefy.",
            2: "Sterowane przewietrzanie naturalne skoordynowane z HVAC.",
            3: "Zautomatyzowane, zoptymalizowane przewietrzanie (np. nocne) z predykcja.",
        },
        "technologies": ["kontaktrony okienne", "napedy okien/klap", "logika blokady HVAC", "night ventilation"],
        "devices": ["czujniki otwarcia okna (kontaktrony)", "silowniki okien/klap oddymiajacych", "sterowniki stref/BMS"],
        "audit_verification": ["sprawdz detekcje otwarcia okien i blokade HVAC", "ustal, czy istnieje sterowane przewietrzanie", "zweryfikuj automatyzacje nocnego przewietrzania (poziom 3)"],
        "evidence": ["schemat kontaktronow/napedow", "logika blokady w BMS", "trendy stanu okien vs praca HVAC"],
        "common_mistakes": ["brak blokady HVAC przy otwartym oknie", "napedy okien bez zabezpieczen pogodowych (deszcz/wiatr)", "przewietrzanie kolidujace z komfortem"],
        "limitations": ["wymaga czujnikow/napedow okien", "ograniczenia bezpieczenstwa i pogodowe"],
        "dependencies": ["H-1a/C-1a (blokada grzania/chlodzenia strefy)", "V-3 (free-cooling/przewietrzanie)", "DE-1 (zacienienie)"],
        "cross_domain_impact": ["ogrzewanie/chlodzenie (blokada przy otwartym oknie)", "wentylacja (przewietrzanie naturalne)"],
        "modernization": ["montaz kontaktronow i blokady HVAC", "automatyzacja przewietrzania nocnego", "koordynacja z wentylacja mechaniczna"],
        "examples": ["biuro z blokada fan-coila przy otwartym oknie", "budynek z automatycznym nocnym przewietrzaniem klapami"],
    },
    "DE-4": {
        "friendly_name": "Raportowanie pracy dynamicznej powloki budynku",
        "purpose": "Dostarczanie informacji o dzialaniu oslon i elementow ruchomych powloki, aby monitorowac ich skutecznosc i wykrywac usterki.",
        "technical": "Zbieranie i prezentacja danych o pracy zacienienia/okien: pozycje, cykle, awarie; wyzsze poziomy z analiza skutecznosci i alarmami.",
        "energy_significance": "Monitoring ujawnia niedzialajace/zablokowane oslony i pozwala utrzymac ich wklad w redukcje zyskow ciepla i komfort.",
        "level_notes": {
            0: "Brak raportowania powloki.",
            1: "Podstawowa informacja o stanie oslon/okien.",
            2: "Rejestracja i historia pracy elementow powloki.",
            3: "Analiza skutecznosci i sygnalizacja odchylen.",
            4: "Pelne raportowanie ze wsparciem optymalizacji i diagnostyki.",
        },
        "technologies": ["monitoring pozycji napedow", "historian/trendy", "dashboardy", "diagnostyka napedow"],
        "devices": ["napedy z informacja zwrotna o pozycji", "czujniki stanu", "koncentrator danych/BMS"],
        "audit_verification": ["sprawdz, czy pozycje/stany oslon sa raportowane", "zweryfikuj historie i alarmy usterek", "ustal analize skutecznosci (wyzsze poziomy)"],
        "evidence": ["dashboard stanu powloki", "logi cykli/awarii napedow", "trendy pozycji"],
        "common_mistakes": ["brak informacji zwrotnej z napedow", "dane bez alarmow o awariach", "brak powiazania ze skutecznoscia energetyczna"],
        "limitations": ["wymaga napedow z informacja zwrotna", "jakosc zalezy od opomiarowania"],
        "dependencies": ["DE-1 (zacienienie)", "DE-2 (okna)", "MC-13 (centralne raportowanie)", "MC-4 (detekcja usterek)"],
        "cross_domain_impact": ["monitoring i sterowanie (dane do MC-13/MC-4)", "chlodzenie/oswietlenie (skutecznosc zacienienia)"],
        "modernization": ["napedy z informacja zwrotna o pozycji", "dashboard i alarmy usterek oslon", "analiza skutecznosci zacienienia"],
        "examples": ["fasada z monitoringiem pozycji zaluzji i alarmami awarii napedow"],
    },
}
