# -*- coding: utf-8 -*-
"""Tresc ekspercka SRI — domena: Ladowanie pojazdow elektrycznych (EV charging). 3 uslugi."""

EXPERT = {
    "EV-15": {
        "friendly_name": "Infrastruktura i moc ladowania EV",
        "purpose": "Zapewnienie odpowiedniej liczby i mocy punktow ladowania pojazdow elektrycznych z inteligentnym zarzadzaniem moca (nieprzeciazanie przylacza).",
        "technical": "Zarzadzanie ladowaniem EV: od braku, przez pojedyncze punkty, po dynamiczne zarzadzanie moca (load balancing) rozdzielajace dostepna moc miedzy pojazdy i pozostale odbiory.",
        "energy_significance": "Dynamiczny load balancing pozwala ladowac wiecej pojazdow bez rozbudowy przylacza i unika drogich szczytow mocy; umozliwia ladowanie z nadwyzek OZE.",
        "level_notes": {
            0: "Brak infrastruktury EV lub ladowanie niesterowane.",
            1: "Podstawowe punkty ladowania (stala moc).",
            2: "Sterowanie moca pojedynczych punktow (harmonogram/limit).",
            3: "Dynamiczne zarzadzanie moca miedzy punktami (load balancing).",
            4: "Zaawansowane, zoptymalizowane zarzadzanie (OZE/taryfy/priorytety uzytkownikow).",
        },
        "technologies": ["load balancing (statyczny/dynamiczny)", "OCPP", "integracja z licznikiem przylacza", "sterowanie wg PV/taryf"],
        "devices": ["stacje ladowania (wallbox/AC/DC)", "licznik przylacza", "kontroler load balancing/EMS"],
        "audit_verification": ["ustal liczbe i moc punktow oraz sposob zarzadzania moca", "sprawdz load balancing wzgledem przylacza", "zweryfikuj integracje z PV/taryfami (poziom 4)"],
        "evidence": ["schemat instalacji EV i przylacza", "konfiguracja load balancing/OCPP", "trendy mocy ladowania vs limit przylacza"],
        "common_mistakes": ["brak load balancingu (ryzyko przeciazenia)", "stala moc bez uwzglednienia szczytow", "brak integracji z PV mimo dostepnosci"],
        "limitations": ["ograniczenia mocy przylacza", "standardy zlaczy/protokolow", "zaleznosc od zachowan uzytkownikow"],
        "dependencies": ["EV-16 (bilansowanie sieci)", "EV-17 (informacja/laczonosc)", "E-4 (autokonsumpcja PV)", "MC-25 (smart grid)"],
        "cross_domain_impact": ["elektrycznosc (EV jako duzy, sterowalny odbiornik)", "elastycznosc energetyczna"],
        "modernization": ["wdrozenie dynamicznego load balancingu", "integracja ladowania z nadwyzka PV i taryfami", "rozbudowa o OCPP i priorytety"],
        "examples": ["parking biurowy z dynamicznym load balancingiem i OCPP", "obiekt ladujacy EV z nadwyzki PV"],
    },
    "EV-16": {
        "friendly_name": "Bilansowanie sieci przez ladowanie EV",
        "purpose": "Wykorzystanie ladowania (i ewentualnie rozladowania V2G) pojazdow do wspierania sieci — przesuwanie poboru, redukcja szczytow, uslugi elastycznosci.",
        "technical": "Sterowanie ladowaniem EV wg sygnalow sieci/taryf (smart charging), a na wyzszym poziomie dwukierunkowo (V2G/V2B) — od braku, przez smart charging, po pelne uslugi sieciowe.",
        "energy_significance": "EV to duzy, przesuwalny odbiornik (i potencjalny magazyn) — jego elastycznosc obniza koszty, szczyty i wspiera stabilnosc sieci; wysoka waga w SRI.",
        "level_notes": {
            0: "Brak bilansowania (ladowanie niesterowane sygnalami).",
            1: "Smart charging wg taryf/sygnalow (jednokierunkowo).",
            2: "Dwukierunkowa wspolpraca (V2G/V2B) / uslugi sieciowe.",
        },
        "technologies": ["smart charging", "V2G/V2B", "OCPP/OpenADR", "integracja z EMS i sygnalami sieci"],
        "devices": ["stacje ladowania z funkcja smart/V2G", "licznik dwukierunkowy", "EMS/kontroler", "brama sygnalow sieci"],
        "audit_verification": ["sprawdz reakcje ladowania na taryfy/sygnaly sieci", "ustal, czy dostepne jest V2G/V2B", "zweryfikuj uslugi sieciowe i rozliczenia (poziom 2)"],
        "evidence": ["konfiguracja smart charging/V2G", "trendy poboru EV vs ceny/sygnaly", "umowy uslug elastycznosci"],
        "common_mistakes": ["ladowanie w szczycie bez sterowania", "deklaracja smart charging bez realnego sygnalu", "brak koordynacji z load balancingiem"],
        "limitations": ["dostepnosc V2G zalezna od pojazdow/stacji", "aspekty formalne uslug sieciowych", "zachowania uzytkownikow"],
        "dependencies": ["EV-15 (infrastruktura/moc)", "E-3 (magazyn)", "MC-25 (smart grid)", "MC-29 (override DSM)"],
        "cross_domain_impact": ["elektrycznosc (elastycznosc i magazynowanie)", "elastycznosc energetyczna", "monitoring (DSM)"],
        "modernization": ["wdrozenie smart charging wg taryf/sieci", "pilotaz V2G/V2B", "integracja z EMS i uslugami elastycznosci"],
        "examples": ["flota sluzbowa ladowana wg cen energii i sygnalow sieci", "obiekt z pilotazem V2B wspierajacym szczyty"],
    },
    "EV-17": {
        "friendly_name": "Informacja i laczonosc ladowania EV",
        "purpose": "Udostepnianie uzytkownikom i systemom informacji o ladowaniu (status, koszt, dostepnosc) oraz laczonosci umozliwiajacej zdalne zarzadzanie i rozliczenia.",
        "technical": "Funkcje informacyjne i komunikacyjne stacji: status sesji, identyfikacja/autoryzacja, rozliczenia, integracja z systemami; od braku, przez podstawowa informacje, po pelna laczonosc i integracje.",
        "energy_significance": "Laczonosc i informacja umozliwiaja smart charging, rozliczenia i optymalizacje uzycia — warunek zaawansowanego zarzadzania i elastycznosci EV.",
        "level_notes": {
            0: "Brak informacji/laczonosci (stacja offline).",
            1: "Podstawowa informacja o statusie ladowania.",
            2: "Pelna laczonosc i integracja (autoryzacja, rozliczenia, zdalne zarzadzanie).",
        },
        "technologies": ["OCPP", "aplikacje/portale uzytkownika", "autoryzacja RFID/aplikacja", "integracja z systemami rozliczen"],
        "devices": ["stacje ladowania z laczonoscia", "czytniki RFID", "brama/backend zarzadzania ladowaniem"],
        "audit_verification": ["sprawdz laczonosc stacji (OCPP/backend)", "ustal dostepnosc informacji dla uzytkownikow (status/koszt)", "zweryfikuj autoryzacje i rozliczenia (poziom 2)"],
        "evidence": ["konfiguracja OCPP/backendu", "zrzuty aplikacji/portalu", "raporty sesji ladowania"],
        "common_mistakes": ["stacje offline (brak zarzadzania)", "brak autoryzacji (niekontrolowane uzycie)", "brak danych do rozliczen"],
        "limitations": ["zaleznosc od backendu/operatora", "kwestie ochrony danych uzytkownikow"],
        "dependencies": ["EV-15 (infrastruktura)", "EV-16 (smart charging)", "MC-13 (raportowanie)"],
        "cross_domain_impact": ["monitoring i sterowanie (dane sesji, integracja)", "elastycznosc energetyczna (warunek smart charging)"],
        "modernization": ["wdrozenie OCPP i backendu zarzadzania", "aplikacja/portal dla uzytkownikow", "autoryzacja i rozliczenia sesji"],
        "examples": ["parking z ladowarkami OCPP, autoryzacja RFID i rozliczeniami", "obiekt z portalem statusu i rezerwacji ladowarek"],
    },
}
