# -*- coding: utf-8 -*-
"""Tresc ekspercka SRI — domena: Ogrzewanie (Heating). 10 uslug.
Pola urzedowe (nazwa, poziomy) dokladane sa z katalogu przez build_knowledge.py."""

EXPERT = {
    # ─────────────────────────────────────────────────────────────────────────
    "H-1a": {
        "friendly_name": "Sterowanie ogrzewaniem w pomieszczeniach",
        "purpose": "Dostarczanie ciepla do pomieszczen dokladnie w takiej ilosci i wtedy, kiedy jest potrzebne, aby utrzymac komfort przy minimalnym zuzyciu energii.",
        "technical": "Regulacja mocy grzejnikow, ogrzewania podlogowego lub klimakonwektorow w oparciu o temperature zadana i rzeczywista w strefie/pomieszczeniu. Od prostego termostatu centralnego, przez indywidualne sterowanie pomieszczeniami (glowice/termostaty), az po sterowanie komunikujace sie z systemem BMS i uwzgledniajace obecnosc uzytkownikow.",
        "energy_significance": "Jedna z najbardziej oplacalnych uslug — indywidualna regulacja pomieszczen i detekcja obecnosci ograniczaja przegrzewanie i eliminuja grzanie pustych stref, dajac typowo kilkanascie procent oszczednosci na ogrzewaniu.",
        "level_notes": {
            0: "Brak automatyki — zawory reczne, temperatura ustawiana recznie; sterowanie tylko przez uzytkownika.",
            1: "Jeden termostat centralny dla calego budynku/strefy — brak roznicowania pomieszczen.",
            2: "Indywidualna regulacja pomieszczen (glowice termostatyczne lub sterowniki elektroniczne) — kazde pomieszczenie trzyma wlasna temperature.",
            3: "Indywidualna regulacja z komunikacja miedzy sterownikami i z BMS — harmonogramy, zdalna zmiana nastaw, koordynacja stref.",
            4: "Jak poziom 3 plus detekcja obecnosci — automatyczne obnizanie temperatury w nieuzywanych pomieszczeniach.",
        },
        "technologies": ["KNX", "Loxone", "Modbus", "bezprzewodowe glowice (Zigbee/EnOcean)", "termostaty komunikacyjne", "integracja z BMS/BACS"],
        "devices": ["glowice termostatyczne elektroniczne", "termostaty pokojowe", "sterowniki stref ogrzewania podlogowego (listwy)", "czujniki temperatury i obecnosci", "sterowniki pomieszczeniowe KNX/Loxone"],
        "audit_verification": [
            "Sprawdz, czy pomieszczenia maja niezalezne zadawanie temperatury (glowice/termostaty).",
            "Zapytaj, czy istnieja harmonogramy dobowe/tygodniowe i gdzie sa konfigurowane.",
            "Sprawdz w systemie, czy sterowniki komunikuja sie z BMS (widocznosc nastaw i temperatur).",
            "Zweryfikuj obecnosc czujnikow obecnosci powiazanych z ogrzewaniem (poziom 4).",
        ],
        "evidence": ["zrzuty ekranu z BMS z nastawami per pomieszczenie", "lista punktow (I/O) w sterowniku", "schemat instalacji AKPiA", "zdjecia glowic/termostatow z modelami", "projekt automatyki / DTR"],
        "common_mistakes": [
            "Czujnik temperatury zamontowany w zlym miejscu (nad grzejnikiem, w przeciagu, na scianie zewnetrznej).",
            "Glowice ustawione na sztywno lub zdemontowane przez uzytkownikow.",
            "Brak realnych harmonogramow — system dziala 24/7 na jednej nastawie.",
            "Detekcja obecnosci deklarowana, ale niepodlaczona do logiki grzania.",
        ],
        "limitations": ["bezwladnosc ogrzewania podlogowego ogranicza skutecznosc szybkich zmian nastaw", "w TABS stosuje sie osobna usluge H-1b (triage)", "stare instalacje jednorurowe utrudniaja indywidualna regulacje"],
        "dependencies": ["H-1c (temperatura zasilania)", "H-2a/H-2b (zrodlo ciepla)", "MC-3 (harmonogramy/run-time)", "DE-2 (blokada grzania przy otwartym oknie)"],
        "cross_domain_impact": ["chlodzenie (C-1f: blokada jednoczesnego grzania i chlodzenia)", "wentylacja (koordynacja komfortu cieplnego)", "monitoring (MC-30: optymalizacja wg obecnosci/pogody)"],
        "modernization": ["wymiana glowic recznych na elektroniczne komunikacyjne", "dodanie czujnikow obecnosci w salach konferencyjnych/biurach", "integracja termostatow z BMS i wprowadzenie harmonogramow", "strefowanie ogrzewania podlogowego"],
        "examples": ["biuro z glowicami KNX i harmonogramem pracy 7-18", "mieszkanie z termostatami pokojowymi Loxone i detekcja obecnosci", "szkola z obnizaniem temperatury w salach poza planem lekcji"],
    },
    # ─────────────────────────────────────────────────────────────────────────
    "H-1b": {
        "friendly_name": "Sterowanie ogrzewaniem plaszczyznowym TABS",
        "purpose": "Regulacja ogrzewania aktywowanego termicznie w konstrukcji budynku (betonowe rdzenie/stropy) tak, aby wykorzystac bezwladnosc masy do stabilnego, taniego ogrzewania.",
        "technical": "Sterowanie ukladami TABS (thermally activated building systems) — ogrzewanie zatopione w stropach/scianach. Ze wzgledu na duza bezwladnosc reguluje sie glownie temperatura zasilania i harmonogramami z wyprzedzeniem, opcjonalnie z predykcja pogody.",
        "energy_significance": "TABS pozwala grzac woda o niskiej temperaturze i przesuwac pobor energii w czasie (magazyn ciepla w masie), co sprzyja pompom ciepla i taryfom nocnym oraz obniza szczyty mocy.",
        "level_notes": {
            0: "Brak automatyki — reczne lub stalotemperaturowe zasilanie TABS.",
            1: "Centralne sterowanie automatyczne (np. wg krzywej grzewczej/harmonogramu).",
            2: "Sterowanie z uwzglednieniem stref lub warunkow wewnetrznych/zewnetrznych.",
            3: "Zaawansowane sterowanie predykcyjne (pogoda, oblozenie) wykorzystujace bezwladnosc masy.",
        },
        "technologies": ["sterowniki BMS z krzywa grzewcza", "regulacja predykcyjna (pogoda)", "Modbus/BACnet", "zawory mieszajace z silownikami"],
        "devices": ["zawory mieszajace 3-drogowe z silownikami", "czujniki temperatury zasilania i pomieszczen", "stacja pogodowa", "sterownik strefy TABS"],
        "audit_verification": ["ustal, czy budynek ma TABS (stropy/sciany aktywowane termicznie)", "sprawdz sposob regulacji temperatury zasilania i istnienie harmonogramow z wyprzedzeniem", "zweryfikuj integracje z prognoza pogody (poziom 3)"],
        "evidence": ["projekt instalacji TABS", "schemat wezla mieszajacego", "konfiguracja krzywej grzewczej w BMS", "trendy temperatur zasilania"],
        "common_mistakes": ["sterowanie TABS jak zwyklym ogrzewaniem (za szybkie zmiany nastaw)", "brak wyprzedzenia czasowego wzgledem oblozenia", "jednoczesne grzanie TABS i doziebianie tej samej strefy"],
        "limitations": ["bardzo duza bezwladnosc — reakcja liczona w godzinach", "trudna szybka korekta komfortu", "wystepuje tylko w budynkach z TABS (triage wzgledem H-1a)"],
        "dependencies": ["H-1c (temperatura zasilania)", "C-1b (TABS w trybie chlodzenia)", "C-1f (blokada grzanie/chlodzenie)", "MC-30 (optymalizacja predykcyjna)"],
        "cross_domain_impact": ["chlodzenie (ten sam uklad TABS bywa wspoldzielony)", "elastycznosc energetyczna (magazyn ciepla w masie budynku)"],
        "modernization": ["dodanie regulacji predykcyjnej wg pogody i oblozenia", "rozdzielenie stref TABS", "integracja z taryfami/sygnalami sieci"],
        "examples": ["biurowiec klasy A z aktywowanymi termicznie stropami i sterowaniem predykcyjnym", "budynek uzytecznosci publicznej z TABS ladowanym noca"],
    },
    # ─────────────────────────────────────────────────────────────────────────
    "H-1c": {
        "friendly_name": "Regulacja temperatury czynnika grzewczego",
        "purpose": "Dopasowanie temperatury wody/powietrza w instalacji do rzeczywistego zapotrzebowania budynku (kompensacja pogodowa), zamiast grzania stala, wysoka temperatura.",
        "technical": "Regulacja temperatury zasilania w oparciu o krzywa grzewcza (temperatura zewnetrzna) lub o zapotrzebowanie stref. Dotyczy tez sterowania bezposrednim ogrzewaniem elektrycznym.",
        "energy_significance": "Nizsza temperatura zasilania to mniejsze straty dystrybucji i wyzsza sprawnosc zrodel kondensacyjnych oraz pomp ciepla — jeden z podstawowych mechanizmow oszczednosci.",
        "level_notes": {
            0: "Stala temperatura zasilania — brak dostosowania do warunkow.",
            1: "Kompensacja wg temperatury zewnetrznej (krzywa grzewcza) lub prosty harmonogram.",
            2: "Regulacja wg zapotrzebowania (np. na podstawie sygnalow ze stref/zaworow), dynamiczne dostosowanie krzywej.",
        },
        "technologies": ["regulacja pogodowa (krzywa grzewcza)", "regulacja wg zadania stref", "sterowniki wezlow cieplnych", "Modbus/BACnet"],
        "devices": ["czujnik temperatury zewnetrznej", "czujnik temperatury zasilania/powrotu", "zawor mieszajacy z silownikiem", "sterownik wezla"],
        "audit_verification": ["sprawdz, czy istnieje czujnik zewnetrzny i aktywna krzywa grzewcza", "zweryfikuj, czy temperatura zasilania zmienia sie z pogoda (trendy)", "ustal, czy regulacja reaguje na zapotrzebowanie stref (poziom 2)"],
        "evidence": ["konfiguracja krzywej grzewczej", "trendy temperatur zasilania vs zewnetrznej", "schemat wezla cieplnego"],
        "common_mistakes": ["zbyt wysoko ustawiona krzywa 'na zapas'", "czujnik zewnetrzny w naslonecznionym/cieplym miejscu", "brak korekty krzywej po termomodernizacji"],
        "limitations": ["skutecznosc zalezy od poprawnego zrownowazenia hydraulicznego", "ograniczona przy wspoldzieleniu obiegow o roznych wymaganiach"],
        "dependencies": ["H-1a/H-1b (odbior ciepla w strefach)", "H-1d (pompy obiegowe)", "H-2a/H-2b (zrodlo)"],
        "cross_domain_impact": ["efektywnosc zrodla ciepla i pomp ciepla (wspolny efekt z domena elektrycznosci przy PC)"],
        "modernization": ["wdrozenie/optymalizacja krzywej grzewczej", "obnizenie temperatury zasilania po dociepleniu", "regulacja wg zapotrzebowania stref"],
        "examples": ["wezel cieplny z kompensacja pogodowa", "instalacja z pompa ciepla i obnizona krzywa dla podlogowki"],
    },
    # ─────────────────────────────────────────────────────────────────────────
    "H-1d": {
        "friendly_name": "Sterowanie pompami obiegowymi ogrzewania",
        "purpose": "Ograniczenie energii elektrycznej pomp obiegowych przez dopasowanie ich pracy do rzeczywistego przeplywu wymaganego przez instalacje.",
        "technical": "Sterowanie pompami: od staloobrotowych zalacz/wylacz, przez pompy o zmiennej predkosci (falownik) ze stalym cisnieniem, po regulacje wg zmiennego cisnienia/przeplywu na podstawie zapotrzebowania.",
        "energy_significance": "Pompy o zmiennej predkosci sterowane wg zapotrzebowania zuzywaja wielokrotnie mniej energii niz pompy staloobrotowe pracujace ciagle — szybki zwrot z modernizacji.",
        "level_notes": {
            0: "Pompa staloobrotowa pracujaca w sposob ciagly.",
            1: "Zalaczanie/wylaczanie pompy wg zapotrzebowania (on/off).",
            2: "Pompa o zmiennej predkosci ze stala roznica cisnien.",
            3: "Pompa o zmiennej predkosci ze zmienna roznica cisnien (proporcjonalna).",
            4: "Regulacja wg rzeczywistego zapotrzebowania stref (sygnaly z zaworow/BMS).",
        },
        "technologies": ["pompy elektroniczne (falownik)", "regulacja proporcjonalna cisnienia", "sygnaly z zaworow strefowych", "Modbus/analog 0-10V"],
        "devices": ["pompy obiegowe z regulacja predkosci", "czujniki cisnienia/roznicy cisnien", "przetworniki przeplywu", "sterownik/BMS"],
        "audit_verification": ["sprawdz typ pomp (staloobrotowe vs elektroniczne)", "ustal tryb regulacji (stale/zmienne cisnienie, wg zapotrzebowania)", "zweryfikuj, czy pompa wylacza sie przy braku zapotrzebowania"],
        "evidence": ["tabliczki/DTR pomp", "nastawy trybu pracy pompy", "trendy poboru mocy/predkosci pompy"],
        "common_mistakes": ["pozostawienie pompy w trybie stalej predkosci", "przewymiarowanie pomp", "brak powiazania pracy pompy z zapotrzebowaniem stref"],
        "limitations": ["korzysc zalezy od zmiennosci obciazenia instalacji", "wymaga poprawnego zrownowazenia hydraulicznego"],
        "dependencies": ["H-1a (odbior w strefach generuje zapotrzebowanie)", "H-1c (temperatura zasilania)", "H-3 (raportowanie pracy)"],
        "cross_domain_impact": ["elektrycznosc (redukcja poboru pomocniczej energii elektrycznej)"],
        "modernization": ["wymiana pomp staloobrotowych na elektroniczne", "przejscie na regulacje proporcjonalna/wg zapotrzebowania", "wylaczanie pomp poza sezonem/przy braku rozbioru"],
        "examples": ["kotlownia z pompami elektronicznymi ze zmiennym cisnieniem", "instalacja ze sterowaniem pomp wg otwarcia zaworow strefowych"],
    },
    # ─────────────────────────────────────────────────────────────────────────
    "H-1f": {
        "friendly_name": "Magazyn ciepla (bufor) dla ogrzewania",
        "purpose": "Gromadzenie ciepla w zasobniku, aby oddzielic prace zrodla od chwilowego zapotrzebowania — stabilizacja pracy, wykorzystanie tanszej energii i integracja OZE.",
        "technical": "Sterowanie ladowaniem/rozladowaniem bufora ciepla (poza TABS). Od braku sterowania, przez sterowanie wg harmonogramu/temperatury, po sterowanie uwzgledniajace sygnaly zewnetrzne (pogoda, taryfy, dostepnosc OZE).",
        "energy_significance": "Bufor pozwala pompie ciepla/kotlowi pracowac w optymalnym punkcie i przesuwac pobor energii na godziny tanie lub z nadwyzka PV, obnizajac koszty i szczyty mocy.",
        "level_notes": {
            0: "Brak magazynu lub brak sterowania jego ladowaniem.",
            1: "Sterowanie ladowaniem wg temperatury/harmonogramu.",
            2: "Optymalizacja ladowania wg zapotrzebowania i warunkow (np. pogoda).",
            3: "Ladowanie sterowane sygnalami zewnetrznymi (taryfy/siec/OZE) — funkcja elastycznosci.",
        },
        "technologies": ["zasobniki buforowe", "sterowanie warstwowaniem (stratyfikacja)", "integracja z taryfami/sygnalami sieci", "sterowanie wg nadwyzki PV"],
        "devices": ["zasobnik buforowy", "czujniki temperatury w warstwach zbiornika", "zawory przelaczajace", "sterownik/BMS"],
        "audit_verification": ["ustal obecnosc i pojemnosc bufora", "sprawdz logike ladowania (harmonogram, temperatura, sygnaly zewnetrzne)", "zweryfikuj powiazanie z PV/taryfami (poziom 3)"],
        "evidence": ["schemat hydrauliczny z buforem", "konfiguracja logiki ladowania", "trendy temperatur w zbiorniku"],
        "common_mistakes": ["zbyt maly lub zbyt duzy bufor", "brak stratyfikacji (mieszanie warstw)", "ladowanie w drogich godzinach szczytu"],
        "limitations": ["straty postojowe zbiornika", "miejsce w kotlowni", "korzysc zalezy od zmiennosci taryf/udzialu OZE"],
        "dependencies": ["H-2a/H-2b (zrodlo ciepla)", "H-4 (elastycznosc/siec)", "E-3 (magazyn energii elektrycznej — komplementarnosc)"],
        "cross_domain_impact": ["elektrycznosc (autokonsumpcja PV przez grzanie bufora)", "elastycznosc energetyczna"],
        "modernization": ["dodanie bufora do instalacji z pompa ciepla", "sterowanie ladowaniem wg nadwyzki PV i taryf", "poprawa stratyfikacji zbiornika"],
        "examples": ["dom z pompa ciepla i buforem ladowanym z PV", "kotlownia z buforem ladowanym w taryfie nocnej"],
    },
    # ─────────────────────────────────────────────────────────────────────────
    "H-2a": {
        "friendly_name": "Sterowanie zrodlem ciepla (poza pompami ciepla)",
        "purpose": "Regulacja pracy kotla/wymiennika tak, aby produkowal cieplo o odpowiedniej temperaturze i mocy zgodnie z zapotrzebowaniem, przy wysokiej sprawnosci.",
        "technical": "Sterowanie generatorem ciepla (kociol gazowy/olejowy, wezel cieplny) — od stalej temperatury, przez sterowanie zmienne zaleznie od obciazenia lub temperatury zewnetrznej.",
        "energy_significance": "Dostosowanie temperatury i mocy zrodla do potrzeb podnosi sprawnosc (zwlaszcza kondensacja) i ogranicza taktowanie oraz straty postojowe.",
        "level_notes": {
            0: "Sterowanie stalotemperaturowe — zrodlo grzeje do stalej wartosci.",
            1: "Sterowanie zmienne wg temperatury zewnetrznej lub obciazenia.",
            2: "Sterowanie zmienne wg zapotrzebowania (sygnaly ze stref/BMS), optymalizacja punktu pracy.",
        },
        "technologies": ["sterowniki kotlowe", "regulacja pogodowa", "modulacja mocy palnika", "Modbus/OpenTherm/BACnet"],
        "devices": ["kociol z modulacja", "sterownik kotla", "czujniki temperatury zasilania i zewnetrznej", "zawory mieszajace"],
        "audit_verification": ["ustal typ zrodla i sposob sterowania temperatura", "sprawdz, czy dziala modulacja/kompensacja", "zweryfikuj reakcje na zapotrzebowanie (poziom 2)"],
        "evidence": ["DTR/tabliczka kotla", "nastawy sterownika kotlowego", "trendy temperatur i modulacji"],
        "common_mistakes": ["kociol pracujacy na stalej, wysokiej temperaturze", "brak kondensacji mimo kotla kondensacyjnego (za wysoki powrot)", "taktowanie przez przewymiarowanie"],
        "limitations": ["ograniczenia zakresu modulacji starszych kotlow", "wystepuje dla zrodel innych niz pompy ciepla (dla PC — H-2b)"],
        "dependencies": ["H-1c (temperatura zasilania)", "H-2d (sekwencja wielu zrodel)", "H-3 (raportowanie)"],
        "cross_domain_impact": ["CWU (wspoldzielenie zrodla — patrz DHW-1b/DHW-2b)"],
        "modernization": ["wymiana na kociol kondensacyjny z modulacja", "wlaczenie kompensacji pogodowej", "obnizenie temperatury powrotu dla kondensacji"],
        "examples": ["kotlownia gazowa z modulacja i regulacja pogodowa", "wezel cieplny miejski ze sterowaniem wg zapotrzebowania"],
    },
    # ─────────────────────────────────────────────────────────────────────────
    "H-2b": {
        "friendly_name": "Sterowanie pompa ciepla",
        "purpose": "Optymalna praca pompy ciepla tak, aby maksymalizowac wspolczynnik efektywnosci (COP/SCOP) przy pokryciu zapotrzebowania na cieplo.",
        "technical": "Sterowanie pompa ciepla z uwzglednieniem temperatury zasilania, warunkow zrodla dolnego i zapotrzebowania. Wyzsze poziomy obejmuja optymalizacje punktu pracy i wspolprace z buforem/OZE.",
        "energy_significance": "Kazdy stopien nizszej temperatury zasilania i unikanie taktowania znaczaco podnosi COP; inteligentne sterowanie PC to duze oszczednosci energii elektrycznej.",
        "level_notes": {
            0: "Brak sterowania optymalizujacego — praca staloparametrowa/on-off.",
            1: "Sterowanie wg temperatury zewnetrznej/obciazenia.",
            2: "Sterowanie wg zapotrzebowania z optymalizacja temperatury zasilania.",
            3: "Zaawansowana optymalizacja punktu pracy (COP), wspolpraca z buforem/OZE/taryfami.",
        },
        "technologies": ["inwerterowe pompy ciepla", "regulacja pogodowa", "optymalizacja COP", "integracja PV/bufor/taryfy", "Modbus/SG-Ready"],
        "devices": ["pompa ciepla inwerterowa", "czujniki temperatur (zasilanie, dolne zrodlo)", "bufor", "sterownik PC/BMS"],
        "audit_verification": ["ustal typ PC (inwerter/on-off) i logike sterowania", "sprawdz temperature zasilania i jej dostosowanie", "zweryfikuj wspolprace z PV/buforem/SG-Ready (poziom 3)"],
        "evidence": ["DTR pompy ciepla", "nastawy sterownika PC", "trendy COP/temperatur", "konfiguracja SG-Ready/PV"],
        "common_mistakes": ["za wysoka temperatura zasilania (niski COP)", "taktowanie przez brak bufora/przewymiarowanie", "brak wykorzystania nadwyzek PV"],
        "limitations": ["COP zalezny od temperatury zrodla dolnego", "ograniczenia mocy przy niskich temperaturach zewnetrznych"],
        "dependencies": ["H-1c (temperatura zasilania)", "H-1f (bufor)", "H-4 (elastycznosc)", "E-4 (autokonsumpcja PV)"],
        "cross_domain_impact": ["elektrycznosc (PC jest duzym odbiornikiem — synergia z PV/magazynem)", "elastycznosc energetyczna (SG-Ready)"],
        "modernization": ["obnizenie temperatury zasilania (wieksze grzejniki/podlogowka)", "dodanie bufora i logiki PV", "aktywacja SG-Ready/sterowania taryfowego"],
        "examples": ["dom z PC inwerterowa, buforem i sterowaniem wg PV", "biurowiec z PC i optymalizacja COP w BMS"],
    },
    # ─────────────────────────────────────────────────────────────────────────
    "H-2d": {
        "friendly_name": "Kaskada / sekwencja wielu zrodel ciepla",
        "purpose": "Optymalne zalaczanie kilku zrodel ciepla (np. pompa ciepla + kociol szczytowy) tak, aby priorytetyzowac najtansze/najbardziej sprawne zrodlo.",
        "technical": "Logika sekwencjonowania i priorytetow generatorow: dobor zrodla wg sprawnosci, kosztu, dostepnosci OZE i warunkow zewnetrznych; rownowazenie czasu pracy.",
        "energy_significance": "Wlasciwa kaskada maksymalizuje udzial taniego/OZE zrodla (np. PC) i uruchamia szczytowe tylko gdy konieczne, obnizajac koszt i emisje.",
        "level_notes": {
            0: "Brak koordynacji — zrodla pracuja niezaleznie.",
            1: "Prosta sekwencja wg stalych priorytetow.",
            2: "Sekwencja wg obciazenia/sprawnosci.",
            3: "Sekwencja z optymalizacja wg kosztu/warunkow (pogoda, OZE).",
            4: "Pelna optymalizacja predykcyjna z rownowazeniem pracy i sygnalami zewnetrznymi.",
        },
        "technologies": ["menedzer kaskady/zrodel w BMS", "optymalizacja kosztowa", "predykcja pogody", "Modbus/BACnet"],
        "devices": ["sterownik nadrzedny kaskady", "liczniki ciepla/energii zrodel", "czujniki temperatur", "zawory przelaczajace"],
        "audit_verification": ["ustal liczbe i typy zrodel", "sprawdz logike priorytetow i warunki przelaczania", "zweryfikuj rownowazenie czasu pracy i kryteria kosztowe (wyzsze poziomy)"],
        "evidence": ["schemat zrodel i kaskady", "konfiguracja priorytetow w BMS", "trendy udzialu poszczegolnych zrodel"],
        "common_mistakes": ["staly priorytet nieuwzgledniajacy sprawnosci/kosztu", "czeste przelaczanie (taktowanie zrodel)", "kociol szczytowy zalaczany zbyt wczesnie"],
        "limitations": ["wymaga opomiarowania zrodel", "zlozonosc rosnie z liczba generatorow"],
        "dependencies": ["H-2a/H-2b (poszczegolne zrodla)", "H-1f (bufor jako element kaskady)", "H-3 (raportowanie udzialu zrodel)"],
        "cross_domain_impact": ["elektrycznosc (priorytet PC wobec kotla)", "elastycznosc energetyczna"],
        "modernization": ["wdrozenie menedzera kaskady z kryterium kosztowym", "dodanie predykcji pogody", "priorytet OZE/PC przed zrodlem szczytowym"],
        "examples": ["uklad hybrydowy PC + kociol gazowy z kaskada kosztowa", "kotlownia z kilkoma kotlami i rownowazeniem motogodzin"],
    },
    # ─────────────────────────────────────────────────────────────────────────
    "H-3": {
        "friendly_name": "Raportowanie pracy systemu grzewczego",
        "purpose": "Dostarczanie informacji o zuzyciu i sprawnosci ogrzewania, aby umozliwic monitoring, wykrywanie odchylen i swiadome decyzje eksploatacyjne.",
        "technical": "Zbieranie i prezentacja danych o pracy ogrzewania: zuzycie ciepla/energii, temperatury, czasy pracy, sprawnosc. Wyzsze poziomy obejmuja benchmarking, alarmy i analize trendow.",
        "energy_significance": "Bez pomiaru nie ma zarzadzania — raportowanie ujawnia marnotrawstwo, umozliwia optymalizacje nastaw i utrzymanie sprawnosci w czasie.",
        "level_notes": {
            0: "Brak raportowania danych o ogrzewaniu.",
            1: "Podstawowe informacje o aktualnym stanie (temperatury, praca).",
            2: "Rejestracja zuzycia i historii (trendy).",
            3: "Analiza/benchmark i sygnalizacja odchylen.",
            4: "Pelne raportowanie z ocena sprawnosci i wsparciem optymalizacji.",
        },
        "technologies": ["liczniki ciepla", "system trendow/historian", "dashboardy energetyczne", "M-Bus/Modbus/BACnet"],
        "devices": ["cieplomierze", "liczniki energii elektrycznej zrodel", "czujniki temperatur", "brama/koncentrator danych"],
        "audit_verification": ["sprawdz, czy istnieja liczniki ciepla i czy dane sa archiwizowane", "zweryfikuj dostepnosc trendow i raportow", "ustal, czy sa alarmy odchylen (wyzsze poziomy)"],
        "evidence": ["zrzuty dashboardow zuzycia", "eksport trendow/raportow", "lista opomiarowania"],
        "common_mistakes": ["brak licznikow ciepla (tylko szacunki)", "dane zbierane, ale nikt ich nie analizuje", "brak jednostek odniesienia (kWh/m2)"],
        "limitations": ["jakosc raportu zalezy od opomiarowania", "wymaga utrzymania systemu i kalibracji licznikow"],
        "dependencies": ["H-1d/H-2a/H-2b (zrodla danych)", "MC-13 (centralne raportowanie TBS)", "MC-4 (detekcja usterek)"],
        "cross_domain_impact": ["monitoring i sterowanie (dane zasilaja MC-13/MC-4)", "efektywnosc calego budynku"],
        "modernization": ["montaz cieplomierzy i licznikow energii", "wdrozenie dashboardu i alarmow odchylen", "benchmarking wskaznikow kWh/m2"],
        "examples": ["kotlownia z cieplomierzami i dashboardem zuzycia", "biurowiec z alarmami przekroczen zuzycia ciepla"],
    },
    # ─────────────────────────────────────────────────────────────────────────
    "H-4": {
        "friendly_name": "Elastycznosc ogrzewania i wspolpraca z siecia",
        "purpose": "Umozliwienie przesuwania poboru energii na ogrzewanie w czasie w odpowiedzi na sygnaly sieci/taryf, wspierajac stabilnosc systemu i obnizajac koszty.",
        "technical": "Reagowanie ogrzewania na sygnaly zewnetrzne (ceny, sygnaly DSM, dostepnosc OZE) poprzez sterowanie zrodlem, buforem i masa budynku. Od braku, przez sterowanie taryfowe, po automatyczna, dwukierunkowa wspolprace z siecia.",
        "energy_significance": "Elastycznosc obniza koszty (praca w tanich godzinach), zwieksza autokonsumpcje OZE i redukuje szczyty mocy — kryterium o wysokiej wadze w metodologii SRI.",
        "level_notes": {
            0: "Brak reakcji na sygnaly zewnetrzne.",
            1: "Sterowanie wg staticznych taryf/harmonogramu cen.",
            2: "Reakcja na zmienne sygnaly cenowe/DSM (przesuwanie poboru).",
            3: "Automatyczna wspolpraca z siecia z wykorzystaniem magazynu ciepla i predykcji.",
            4: "Pelna, zoptymalizowana elastycznosc z rozliczaniem uslug sieciowych.",
        },
        "technologies": ["SG-Ready", "sterowanie taryfowe/cenowe", "OpenADR/sygnaly DSM", "predykcja pogody i cen", "integracja bufor/PV"],
        "devices": ["sterownik elastycznosci/EMS", "bufor ciepla", "licznik dwukierunkowy", "brama sygnalow sieci"],
        "audit_verification": ["ustal, czy ogrzewanie reaguje na taryfy/sygnaly sieci", "sprawdz wykorzystanie bufora/masy do przesuwania poboru", "zweryfikuj automatyzacje i rozliczenia uslug DSM (wyzsze poziomy)"],
        "evidence": ["konfiguracja SG-Ready/taryf w EMS", "trendy poboru vs ceny/sygnaly", "umowy/uslugi DSM"],
        "common_mistakes": ["deklarowany SG-Ready bez realnego podlaczenia sygnalu", "brak magazynu ciepla ograniczajacy elastycznosc", "sterowanie kolidujace z komfortem"],
        "limitations": ["wymaga zrodla/magazynu zdolnego do przesuniec", "zalezy od dostepnosci sygnalow rynkowych/taryf"],
        "dependencies": ["H-1f (bufor)", "H-2b (pompa ciepla SG-Ready)", "E-3 (magazyn energii)", "MC-25 (integracja smart grid)"],
        "cross_domain_impact": ["elektrycznosc (autokonsumpcja PV, redukcja szczytow)", "monitoring (MC-25/MC-28/MC-29 DSM)"],
        "modernization": ["aktywacja SG-Ready i sterowania taryfowego", "dodanie bufora dla przesuwania poboru", "integracja z EMS i sygnalami sieci"],
        "examples": ["dom z PC SG-Ready ladujacy bufor w tanich godzinach", "budynek z EMS przesuwajacym grzanie wg cen energii"],
    },
}
