# -*- coding: utf-8 -*-
"""Tresc ekspercka SRI — domena: Monitorowanie i sterowanie (Monitoring & control). 8 uslug."""

EXPERT = {
    "MC-3": {
        "friendly_name": "Zarzadzanie czasem pracy instalacji (harmonogramy)",
        "purpose": "Zalaczanie i wylaczanie instalacji technicznych (HVAC) zgodnie z rzeczywistym uzytkowaniem budynku, zamiast pracy ciaglej.",
        "technical": "Zarzadzanie czasem pracy: harmonogramy dobowe/tygodniowe, tryby swiateczne, optymalny start/stop (predykcyjne wyprzedzenie wzgledem oblozenia), a na wyzszych poziomach adaptacja wg obecnosci.",
        "energy_significance": "Wylaczanie/ograniczanie instalacji poza godzinami uzytkowania to jedna z najwiekszych i najtanszych oszczednosci; optymalny start unika przegrzewania przed otwarciem.",
        "level_notes": {
            0: "Praca ciagla / reczne zalaczanie (brak harmonogramow).",
            1: "Harmonogramy czasowe (dobowe/tygodniowe).",
            2: "Optymalny start/stop wg warunkow (wyprzedzenie).",
            3: "Adaptacyjne zarzadzanie czasem pracy wg obecnosci/uzytkowania.",
        },
        "technologies": ["harmonogramy w BMS", "optymalny start/stop", "kalendarze/tryby swiateczne", "integracja obecnosci"],
        "devices": ["sterowniki BMS/PLC", "zegary/kalendarze", "czujniki obecnosci", "sterowniki central/zrodel"],
        "audit_verification": ["sprawdz istnienie i realnosc harmonogramow dla HVAC", "ustal optymalny start/stop", "zweryfikuj adaptacje wg obecnosci (poziom 3)"],
        "evidence": ["konfiguracja harmonogramow w BMS", "trendy pracy vs godziny uzytkowania", "kalendarze/tryby"],
        "common_mistakes": ["praca 24/7 mimo uzytkowania 8-18", "harmonogramy nieaktualne po zmianie uzytkowania", "brak trybu swiatecznego/urlopowego"],
        "limitations": ["bezwladnosc instalacji (potrzebny start z wyprzedzeniem)", "wymaga aktualizacji przy zmianie najemcow"],
        "dependencies": ["H-1a/C-1a (odbior stref)", "V-1c (wentylacja)", "MC-30 (koordynacja/optymalizacja)", "MC-9 (obecnosc)"],
        "cross_domain_impact": ["ogrzewanie/chlodzenie/wentylacja/oswietlenie (wspolne harmonogramy)"],
        "modernization": ["wdrozenie realnych harmonogramow i optymalnego start/stop", "tryby swiateczne/urlopowe", "adaptacja wg obecnosci"],
        "examples": ["biurowiec z optymalnym startem HVAC przed przyjsciem pracownikow", "szkola z harmonogramem wg planu lekcji"],
    },
    "MC-4": {
        "friendly_name": "Wykrywanie i diagnostyka usterek (FDD)",
        "purpose": "Automatyczne wykrywanie usterek i nieprawidlowosci instalacji technicznych oraz wsparcie diagnozy, aby szybko przywracac sprawnosc i unikac strat energii.",
        "technical": "Funkcje FDD (Fault Detection and Diagnosis): reguly/analiza danych wykrywajace odchylenia, awarie, dryf nastaw; wyzsze poziomy z diagnoza przyczyn i priorytetyzacja.",
        "energy_significance": "Niewykryte usterki (zawory, czujniki, jednoczesne grzanie/chlodzenie) powoduja duze, ukryte straty; FDD utrzymuje sprawnosc i obniza koszty eksploatacji.",
        "level_notes": {
            0: "Brak automatycznego wykrywania usterek.",
            1: "Podstawowe alarmy (progi/awarie urzadzen).",
            2: "Wykrywanie odchylen i nieprawidlowosci pracy (reguly FDD).",
            3: "Diagnoza przyczyn i wsparcie usuwania usterek (priorytetyzacja).",
        },
        "technologies": ["FDD (reguly/analityka)", "alarmy i powiadomienia", "analiza trendow/anomalii", "CMMS/integracja serwisu"],
        "devices": ["BMS z modulem alarmow/FDD", "czujniki procesowe", "koncentrator danych/serwer analityki"],
        "audit_verification": ["sprawdz obecnosc alarmow i regul FDD", "ustal, czy wykrywane sa odchylenia (nie tylko awarie)", "zweryfikuj diagnoze przyczyn i obsluge zgloszen (poziom 3)"],
        "evidence": ["lista alarmow/regul FDD", "raporty wykrytych usterek", "integracja z systemem serwisowym"],
        "common_mistakes": ["tylko alarmy awaryjne (brak wykrywania odchylen)", "zalew alarmow bez priorytetow", "alarmy ignorowane (brak procesu obslugi)"],
        "limitations": ["skutecznosc zalezy od jakosci danych/czujnikow", "wymaga konfiguracji regul i utrzymania"],
        "dependencies": ["MC-13 (dane/raportowanie)", "H-3/C-3/DHW-3 (dane domenowe)", "MC-30 (platforma)"],
        "cross_domain_impact": ["wszystkie domeny (diagnostyka calego TBS)", "utrzymanie sprawnosci energetycznej"],
        "modernization": ["wdrozenie regul FDD ponad podstawowe alarmy", "priorytetyzacja i proces obslugi zgloszen", "integracja z CMMS"],
        "examples": ["biurowiec z FDD wykrywajacym jednoczesne grzanie/chlodzenie i zablokowane zawory"],
    },
    "MC-9": {
        "friendly_name": "Detekcja obecnosci dla wielu systemow",
        "purpose": "Wspoldzielona informacja o obecnosci osob wykorzystywana przez rozne instalacje (HVAC, oswietlenie, wentylacja) do sterowania wg rzeczywistego uzytkowania.",
        "technical": "Zbieranie i udostepnianie danych o obecnosci z czujnikow/systemow (ruch, zajetosc, dostep) jako uslugi dla wielu systemow; wyzszy poziom z pelna integracja i wykorzystaniem przez liczne TBS.",
        "energy_significance": "Jedna wiarygodna informacja o obecnosci pozwala wszystkim instalacjom ograniczac prace w pustych strefach — mnoznikowy efekt oszczednosci.",
        "level_notes": {
            0: "Brak wspoldzielonej detekcji obecnosci.",
            1: "Detekcja obecnosci wykorzystywana przez pojedynczy system.",
            2: "Wspoldzielona detekcja obecnosci zintegrowana z wieloma systemami (connected).",
        },
        "technologies": ["czujniki obecnosci (PIR/ultradzwiek)", "integracja z systemem dostepu/rezerwacji", "magistrale KNX/BACnet", "platforma danych"],
        "devices": ["czujniki obecnosci", "kontrola dostepu", "systemy rezerwacji sal", "brama integracyjna/BMS"],
        "audit_verification": ["sprawdz zrodla danych o obecnosci i ich wspoldzielenie", "ustal, ktore systemy korzystaja z obecnosci", "zweryfikuj integracje wielosystemowa (poziom 2)"],
        "evidence": ["schemat integracji obecnosci", "konfiguracja powiazan (HVAC/oswietlenie/wentylacja)", "trendy obecnosci"],
        "common_mistakes": ["osobne czujniki dla kazdego systemu (brak wspoldzielenia)", "martwe pola/za niska czulosc", "brak wykorzystania danych mimo ich zbierania"],
        "limitations": ["prywatnosc/ochrona danych", "jakosc detekcji zalezna od rozmieszczenia czujnikow"],
        "dependencies": ["L-1a (oswietlenie)", "V-1a (wentylacja DCV)", "H-1a/C-1a (HVAC)", "MC-30 (platforma)"],
        "cross_domain_impact": ["oswietlenie/wentylacja/ogrzewanie/chlodzenie (wspolne wykorzystanie obecnosci)"],
        "modernization": ["konsolidacja detekcji obecnosci jako wspolnej uslugi", "integracja z rezerwacja sal/dostepem", "powiazanie z HVAC/oswietleniem/wentylacja"],
        "examples": ["biuro, gdzie jedna detekcja obecnosci steruje swiatlem, wentylacja i HVAC"],
    },
    "MC-13": {
        "friendly_name": "Centralne raportowanie pracy i zuzycia budynku",
        "purpose": "Zbieranie w jednym miejscu danych o pracy i zuzyciu wszystkich instalacji technicznych, aby umozliwic zarzadzanie energia calym budynkiem.",
        "technical": "Centralny system raportowania (energy management): agregacja danych ze wszystkich domen, dashboardy, raporty, benchmarking; wyzsze poziomy z analiza i wsparciem decyzji.",
        "energy_significance": "Zapewnia caloscowy obraz zuzycia i sprawnosci, umozliwiajac priorytetyzacje dzialan, benchmarking i utrzymanie efektow w czasie.",
        "level_notes": {
            0: "Brak centralnego raportowania.",
            1: "Podstawowe centralne wskazania stanu/zuzycia.",
            2: "Rejestracja i historia z wielu systemow (dashboardy).",
            3: "Analiza, benchmarking i wsparcie decyzji (KPI, alarmy).",
        },
        "technologies": ["platforma energy management/EMS", "historian/dashboardy", "raporty/KPI", "integracja BACnet/Modbus/API"],
        "devices": ["serwer EMS/BMS", "koncentratory danych", "liczniki/analizatory z wielu domen"],
        "audit_verification": ["sprawdz istnienie centralnej platformy raportowej", "ustal zakres integrowanych danych (domeny)", "zweryfikuj dashboardy, KPI i alarmy (wyzsze poziomy)"],
        "evidence": ["zrzuty centralnych dashboardow", "raporty energetyczne", "lista integrowanych systemow/punktow"],
        "common_mistakes": ["dane w silosach (brak agregacji)", "dashboardy bez KPI/benchmarku", "raporty niewykorzystywane w decyzjach"],
        "limitations": ["koszt i zlozonosc integracji wielu systemow", "jakosc zalezy od opomiarowania domen"],
        "dependencies": ["H-3/C-3/DHW-3/DE-4/E-2/E-11/E-12/V-6 (zrodla danych)", "MC-4 (FDD)", "MC-30 (platforma sterowania)"],
        "cross_domain_impact": ["wszystkie domeny (centralny obraz i zarzadzanie)"],
        "modernization": ["wdrozenie centralnej platformy EMS", "agregacja danych ze wszystkich domen", "KPI, benchmarking i alarmy"],
        "examples": ["portfel budynkow z centralnym EMS i benchmarkingiem kWh/m2"],
    },
    "MC-25": {
        "friendly_name": "Integracja ze smart grid",
        "purpose": "Umozliwienie budynkowi komunikacji i wspolpracy z inteligentna siecia energetyczna (odbior sygnalow, uslugi elastycznosci).",
        "technical": "Integracja z siecia: odbior sygnalow cen/DSM, komunikacja dwukierunkowa, koordynacja odbiorow/zrodel/magazynow wg sygnalow sieci; od braku, przez odbior sygnalow, po aktywne uslugi.",
        "energy_significance": "Warunek uczestnictwa w elastycznosci energetycznej (kryterium o wysokiej wadze w SRI) — pozwala reagowac na siec i czerpac korzysci rynkowe.",
        "level_notes": {
            0: "Brak integracji ze smart grid.",
            1: "Odbior sygnalow z sieci (ceny/DSM) i reakcja podstawowa.",
            2: "Aktywna, dwukierunkowa wspolpraca i uslugi sieciowe.",
        },
        "technologies": ["OpenADR", "protokoly DSM/rynkowe", "brama smart grid", "integracja z EMS"],
        "devices": ["brama/kontroler smart grid", "licznik dwukierunkowy", "EMS", "sterowane zrodla/odbiory/magazyny"],
        "audit_verification": ["sprawdz, czy budynek odbiera sygnaly sieci/cen", "ustal reakcje odbiorow/zrodel na sygnaly", "zweryfikuj uslugi sieciowe i rozliczenia (poziom 2)"],
        "evidence": ["konfiguracja OpenADR/DSM", "trendy reakcji na sygnaly sieci", "umowy uslug elastycznosci"],
        "common_mistakes": ["brama bez realnego zrodla sygnalow", "reakcja bez koordynacji z komfortem", "brak zasobow elastycznych (magazyn/masa)"],
        "limitations": ["dostepnosc programow DSM/rynkow lokalnie", "wymaga zasobow elastycznych i formalnosci"],
        "dependencies": ["H-4/C-4 (elastycznosc HVAC)", "E-3 (magazyn)", "EV-16 (EV)", "MC-28/MC-29 (DSM)"],
        "cross_domain_impact": ["elastycznosc energetyczna (wszystkie sterowalne odbiory/zrodla)", "elektrycznosc"],
        "modernization": ["wdrozenie bramy smart grid/OpenADR", "koordynacja zasobow elastycznych", "przystapienie do programow DSM"],
        "examples": ["budynek reagujacy na sygnaly OpenADR przez magazyn i HVAC"],
    },
    "MC-28": {
        "friendly_name": "Raportowanie zarzadzania popytem (DSM)",
        "purpose": "Dostarczanie danych o dzialaniach elastycznosci/DSM (kiedy, ile, z jakim efektem), aby oceniac i optymalizowac uslugi sieciowe.",
        "technical": "Zbieranie i prezentacja danych DSM: zdarzenia, przesuniety/zredukowany pobor, efekty finansowe; wyzsze poziomy z analiza skutecznosci.",
        "energy_significance": "Bez raportowania DSM nie da sie ocenic ani rozliczyc elastycznosci — warunek swiadomego udzialu w uslugach sieciowych.",
        "level_notes": {
            0: "Brak raportowania DSM.",
            1: "Podstawowa rejestracja zdarzen/dzialan DSM.",
            2: "Analiza skutecznosci i efektow DSM (raporty/rozliczenia).",
        },
        "technologies": ["rejestracja zdarzen DSM", "dashboardy elastycznosci", "raporty rozliczeniowe", "integracja z EMS/OpenADR"],
        "devices": ["EMS/kontroler DSM", "licznik dwukierunkowy", "koncentrator danych"],
        "audit_verification": ["sprawdz rejestracje zdarzen DSM", "ustal, czy raportowany jest efekt (kWh/koszt)", "zweryfikuj analize skutecznosci (poziom 2)"],
        "evidence": ["raporty zdarzen DSM", "dashboardy przesuniec poboru", "rozliczenia uslug"],
        "common_mistakes": ["brak pomiaru efektu DSM", "dane bez analizy oplacalnosci", "brak powiazania z sygnalami sieci"],
        "limitations": ["wymaga integracji z DSM/rynkiem", "jakosc zalezy od opomiarowania"],
        "dependencies": ["MC-25 (smart grid)", "MC-29 (override DSM)", "E-12 (zuzycie)", "MC-13 (raportowanie)"],
        "cross_domain_impact": ["elastycznosc energetyczna", "elektrycznosc (bilans poboru)"],
        "modernization": ["wdrozenie rejestracji i raportow DSM", "analiza skutecznosci i oplacalnosci", "integracja z EMS/OpenADR"],
        "examples": ["obiekt z raportem zdarzen DSM i efektow finansowych elastycznosci"],
    },
    "MC-29": {
        "friendly_name": "Nadrzedne sterowanie DSM (override)",
        "purpose": "Mozliwosc recznego lub warunkowego nadpisania automatyki DSM, aby chronic komfort/procesy krytyczne podczas zdarzen elastycznosci.",
        "technical": "Funkcje override sterowania DSM: reczne/warunkowe wylaczenie lub modyfikacja reakcji na sygnaly, z zachowaniem priorytetow komfortu/procesow; wyzsze poziomy z granularnoscia i automatyzacja wyjatkow.",
        "energy_significance": "Zaufany mechanizm override zwieksza akceptacje DSM (mozna bezpiecznie uczestniczyc), co posrednio zwieksza realna elastycznosc budynku.",
        "level_notes": {
            0: "Brak mozliwosci nadpisania DSM.",
            1: "Podstawowy reczny override.",
            2: "Override z priorytetami/warunkami (strefy, procesy krytyczne).",
            3: "Granularny, cześciowy override z rejestracja i regulami.",
            4: "Automatyczne, zoptymalizowane zarzadzanie wyjatkami DSM.",
        },
        "technologies": ["mechanizmy override w EMS", "priorytety/reguly wyjatkow", "rejestracja override", "integracja komfort/proces"],
        "devices": ["EMS/kontroler DSM", "panele/przyciski override", "sterowniki stref"],
        "audit_verification": ["sprawdz mozliwosc i zakres override DSM", "ustal priorytety (komfort/procesy krytyczne)", "zweryfikuj rejestracje i reguly wyjatkow (wyzsze poziomy)"],
        "evidence": ["konfiguracja override/priorytetow", "logi zdarzen override", "opis regul wyjatkow"],
        "common_mistakes": ["brak override (spadek akceptacji DSM)", "override globalny bez granularnosci", "brak rejestracji nadpisan"],
        "limitations": ["kompromis miedzy elastycznoscia a komfortem", "wymaga jasnych priorytetow"],
        "dependencies": ["MC-25 (smart grid)", "MC-28 (raportowanie DSM)", "H-4/C-4 (elastycznosc HVAC)"],
        "cross_domain_impact": ["elastycznosc energetyczna (bezpieczne uczestnictwo)", "komfort uzytkownikow"],
        "modernization": ["wdrozenie granularnego override z priorytetami", "rejestracja i reguly wyjatkow", "ochrona procesow krytycznych"],
        "examples": ["szpital z override DSM chroniacym strefy krytyczne", "biuro z czasowym override komfortu podczas zdarzen DSM"],
    },
    "MC-30": {
        "friendly_name": "Jedna platforma sterowania i optymalizacji budynku",
        "purpose": "Zintegrowana platforma (BMS/BACS) koordynujaca wszystkie instalacje i optymalizujaca przeplyw energii wg obecnosci, pogody i sygnalow sieci.",
        "technical": "Wspolna platforma automatyzujaca sterowanie i koordynacje TBS oraz optymalizujaca energie w oparciu o dane (obecnosc, pogoda, ceny/siec); od braku integracji, przez wspolne sterowanie, po pelna optymalizacje predykcyjna.",
        "energy_significance": "Koordynacja miedzydomenowa (np. HVAC + zacienienie + oswietlenie + siec) daje efekty niedostepne dla pojedynczych systemow — najwyzszy poziom inteligencji budynku.",
        "level_notes": {
            0: "Brak wspolnej platformy (systemy niezalezne).",
            1: "Wspolne sterowanie/koordynacja wybranych systemow.",
            2: "Zintegrowana koordynacja wielu TBS z optymalizacja.",
            3: "Pelna optymalizacja predykcyjna (obecnosc, pogoda, siec) miedzy domenami.",
        },
        "technologies": ["BMS/BACS (BACnet/KNX/Modbus)", "platformy optymalizacji/AI", "integracja pogody i sygnalow sieci", "API/IoT"],
        "devices": ["serwer/kontroler BMS", "bramy integracyjne", "stacja pogodowa", "koncentratory danych"],
        "audit_verification": ["sprawdz stopien integracji systemow na jednej platformie", "ustal koordynacje miedzydomenowa", "zweryfikuj optymalizacje predykcyjna (pogoda/obecnosc/siec) (poziom 3)"],
        "evidence": ["architektura integracji/BMS", "opis logiki koordynacji/optymalizacji", "trendy skoordynowanego dzialania systemow"],
        "common_mistakes": ["systemy w silosach (brak realnej koordynacji)", "platforma tylko wizualizujaca (bez optymalizacji)", "brak danych wejsciowych (pogoda/obecnosc)"],
        "limitations": ["koszt/zlozonosc integracji", "roznorodnosc protokolow", "wymaga kompetencji utrzymania"],
        "dependencies": ["MC-3 (harmonogramy)", "MC-9 (obecnosc)", "MC-13 (dane)", "MC-4 (FDD)", "MC-25 (siec)", "wszystkie uslugi domenowe"],
        "cross_domain_impact": ["wszystkie domeny (nadrzedna koordynacja i optymalizacja)"],
        "modernization": ["integracja systemow na wspolnej platformie", "wdrozenie koordynacji miedzydomenowej", "optymalizacja predykcyjna wg pogody/obecnosci/sieci"],
        "examples": ["biurowiec klasy A z BMS koordynujacym HVAC, zacienienie, oswietlenie i reakcje na siec", "obiekt z optymalizacja predykcyjna wg prognoz i oblozenia"],
    },
}
