# -*- coding: utf-8 -*-
"""Tresc ekspercka SRI — domena: Wentylacja (Ventilation). 6 uslug."""

EXPERT = {
    "V-1a": {
        "friendly_name": "Sterowanie strumieniem powietrza w pomieszczeniu",
        "purpose": "Dostarczanie swiezego powietrza do pomieszczen w ilosci odpowiadajacej rzeczywistemu zapotrzebowaniu (obecnosc, CO2, wilgotnosc), zamiast stalej wentylacji.",
        "technical": "Regulacja strumienia powietrza na poziomie pomieszczenia/strefy — od stalego przeplywu, przez sterowanie czasowe, po wentylacje na zadanie (DCV) wg obecnosci lub jakosci powietrza (CO2/VOC/wilgotnosc).",
        "energy_significance": "Wentylacja na zadanie (DCV) eliminuje wentylowanie pustych pomieszczen, oszczedzajac energie wentylatorow oraz ciepla/chlodu na uzdatnianie powietrza.",
        "level_notes": {
            0: "Staly przeplyw powietrza (brak regulacji).",
            1: "Sterowanie czasowe (harmonogram).",
            2: "Sterowanie wg obecnosci (np. detekcja ruchu).",
            3: "Sterowanie wg zapotrzebowania (CO2/wilgotnosc/VOC) — DCV.",
            4: "Zaawansowane DCV z integracja i optymalizacja wielu parametrow.",
        },
        "technologies": ["DCV (Demand Controlled Ventilation)", "przepustnice VAV", "czujniki CO2/VOC/wilgotnosci", "KNX/Modbus/BACnet"],
        "devices": ["przepustnice/regulatory VAV", "czujniki CO2 i obecnosci", "sterowniki pomieszczeniowe", "nawiewniki regulowane"],
        "audit_verification": ["sprawdz obecnosc czujnikow CO2/obecnosci i ich powiazanie ze strumieniem", "ustal, czy przeplyw zmienia sie wg zajetosci", "przejrzyj trendy CO2 vs przeplyw"],
        "evidence": ["schemat VAV/DCV", "nastawy stref w BMS", "trendy CO2 i przeplywu", "zdjecia czujnikow/regulatorow"],
        "common_mistakes": ["czujnik CO2 w niereprezentatywnym miejscu", "staly przeplyw mimo instalacji czujnikow", "brak minimalnej wentylacji higienicznej"],
        "limitations": ["wymaga systemu VAV/regulowanych nawiewnikow", "kalibracja czujnikow CO2 (dryft)"],
        "dependencies": ["V-1c (poziom centrali)", "V-2d (temperatura nawiewu)", "V-6 (raportowanie IAQ)", "MC-9 (detekcja obecnosci)"],
        "cross_domain_impact": ["ogrzewanie/chlodzenie (mniej powietrza = mniej energii na uzdatnianie)", "monitoring (dane IAQ)"],
        "modernization": ["wdrozenie DCV wg CO2/obecnosci", "montaz regulatorow VAV", "kalibracja/wymiana czujnikow CO2"],
        "examples": ["biuro z DCV wg CO2 w salach konferencyjnych", "szkola z wentylacja sterowana obecnoscia i CO2"],
    },
    "V-1c": {
        "friendly_name": "Sterowanie wentylatorami centrali (przeplyw/cisnienie)",
        "purpose": "Dopasowanie pracy wentylatorow centrali (AHU) do sumarycznego zapotrzebowania instalacji, ograniczajac energie wentylatorow.",
        "technical": "Regulacja przeplywu/cisnienia na poziomie centrali wentylacyjnej — od stalej predkosci, przez stale cisnienie, po regulacje wg zapotrzebowania stref (reset cisnienia).",
        "energy_significance": "Energia wentylatorow rosnie z szescianem predkosci — regulacja wg zapotrzebowania i reset cisnienia daja bardzo duze oszczednosci.",
        "level_notes": {
            0: "Wentylatory na stalej predkosci.",
            1: "Zalaczanie/wylaczanie wg zapotrzebowania.",
            2: "Regulacja ze stalym cisnieniem w kanale.",
            3: "Regulacja ze zmiennym cisnieniem (reset wg stref).",
            4: "Optymalizacja wg rzeczywistego zapotrzebowania wszystkich stref.",
        },
        "technologies": ["falowniki wentylatorow", "reset cisnienia kanalowego", "sygnaly z regulatorow VAV", "Modbus/BACnet"],
        "devices": ["wentylatory z falownikiem", "czujniki cisnienia/przeplywu w kanale", "sterownik centrali/BMS"],
        "audit_verification": ["sprawdz regulacje predkosci wentylatorow (falowniki)", "ustal tryb (stale/zmienne cisnienie)", "zweryfikuj reset cisnienia wg zapotrzebowania VAV"],
        "evidence": ["DTR centrali i wentylatorow", "nastawy regulacji cisnienia", "trendy poboru mocy wentylatorow"],
        "common_mistakes": ["wentylatory na stalej predkosci", "zbyt wysokie stale cisnienie", "brak resetu przy systemie VAV"],
        "limitations": ["korzysc zalezy od zmiennosci zapotrzebowania", "wymaga poprawnej regulacji stref"],
        "dependencies": ["V-1a (zapotrzebowanie stref)", "V-2d (temperatura nawiewu)", "V-2c (odzysk ciepla)"],
        "cross_domain_impact": ["elektrycznosc (energia wentylatorow)", "ogrzewanie/chlodzenie (ilosc uzdatnianego powietrza)"],
        "modernization": ["montaz falownikow", "wdrozenie resetu cisnienia wg VAV", "wylaczanie central poza godzinami pracy"],
        "examples": ["centrala VAV z resetem cisnienia wg najbardziej otwartej przepustnicy"],
    },
    "V-2c": {
        "friendly_name": "Sterowanie odzyskiem ciepla (ochrona przed przegrzewem)",
        "purpose": "Sterowanie wymiennikiem odzysku ciepla tak, aby odzyskiwac cieplo/chlod, ale unikac niepozadanego przegrzewania powietrza nawiewanego.",
        "technical": "Regulacja odzysku (obejscie/by-pass, predkosc rotora) z ochrona przed przegrzewem — modulacja odzysku wg roznicy temperatur i zapotrzebowania.",
        "energy_significance": "Odzysk ciepla to jedna z kluczowych oszczednosci w wentylacji; poprawne sterowanie by-passem umozliwia tez free-cooling i unika przegrzewania.",
        "level_notes": {
            0: "Brak sterowania odzyskiem lub staly odzysk (ryzyko przegrzewu).",
            1: "Sterowanie odzyskiem z ochrona przed przegrzewem (by-pass).",
            2: "Modulowane sterowanie odzyskiem z optymalizacja (free-cooling, zapotrzebowanie).",
        },
        "technologies": ["by-pass wymiennika", "modulacja rotora", "free-cooling przez odzysk", "sterowniki central"],
        "devices": ["wymiennik odzysku (rotor/plytowy)", "przepustnica by-pass", "czujniki temperatur (nawiew/wywiew/zewn.)", "sterownik centrali"],
        "audit_verification": ["sprawdz obecnosc i typ odzysku oraz by-passu", "ustal logike ochrony przed przegrzewem", "zweryfikuj wykorzystanie free-coolingu (poziom 2)"],
        "evidence": ["DTR centrali z odzyskiem", "konfiguracja by-passu", "trendy temperatur i sprawnosci odzysku"],
        "common_mistakes": ["brak by-passu (przegrzewanie latem)", "staly odzysk mimo mozliwosci free-coolingu", "oblodzenie wymiennika bez logiki odszraniania"],
        "limitations": ["sprawnosc zalezna od typu wymiennika", "ryzyko przeciekow (rotor)"],
        "dependencies": ["V-2d (temperatura nawiewu)", "V-3 (free-cooling)", "V-1c (przeplyw centrali)"],
        "cross_domain_impact": ["ogrzewanie/chlodzenie (odzysk redukuje zapotrzebowanie)", "elektrycznosc (free-cooling zamiast agregatu)"],
        "modernization": ["dodanie/naprawa by-passu", "wdrozenie free-coolingu przez odzysk", "logika odszraniania"],
        "examples": ["centrala z rotorem i by-passem do free-coolingu nocnego"],
    },
    "V-2d": {
        "friendly_name": "Sterowanie temperatura nawiewu (centrala)",
        "purpose": "Utrzymanie odpowiedniej temperatury powietrza nawiewanego wg zapotrzebowania, aby zapewnic komfort i unikac zbednego grzania/chlodzenia powietrza.",
        "technical": "Regulacja temperatury nawiewu przez nagrzewnice/chlodnice centrali — od stalej temperatury, przez kompensacje wg zewnetrznej, po reset wg zapotrzebowania stref.",
        "energy_significance": "Reset temperatury nawiewu wg realnych potrzeb ogranicza jednoczesne grzanie i chlodzenie powietrza oraz zbedne uzdatnianie.",
        "level_notes": {
            0: "Stala temperatura nawiewu.",
            1: "Kompensacja wg temperatury zewnetrznej/harmonogramu.",
            2: "Reset temperatury nawiewu wg zapotrzebowania stref.",
            3: "Zaawansowana optymalizacja wg wielu stref/warunkow.",
        },
        "technologies": ["reset temperatury nawiewu", "sekwencja nagrzewnica/chlodnica z martwa strefa", "sterowniki central", "BACnet/Modbus"],
        "devices": ["nagrzewnica/chlodnica z zaworami", "czujniki temperatury nawiewu/stref", "sterownik centrali"],
        "audit_verification": ["sprawdz, czy temperatura nawiewu jest stala czy resetowana", "zweryfikuj martwa strefe miedzy nagrzewnica a chlodnica", "przejrzyj trendy temperatur"],
        "evidence": ["nastawy sekwencji grzanie/chlodzenie", "trendy temperatury nawiewu", "schemat centrali"],
        "common_mistakes": ["jednoczesna praca nagrzewnicy i chlodnicy (brak martwej strefy)", "stala, nieoptymalna temperatura nawiewu", "brak resetu wg stref"],
        "limitations": ["ograniczone przy jednej centrali dla roznych stref", "zalezne od regulacji strefowej"],
        "dependencies": ["V-1a/V-1c (przeplyw)", "V-2c (odzysk)", "C-1c/H-1c (parametry mediow)"],
        "cross_domain_impact": ["ogrzewanie/chlodzenie (wspoldzielone media i sekwencje)"],
        "modernization": ["wdrozenie resetu temperatury nawiewu", "wprowadzenie martwej strefy w sekwencji", "kompensacja pogodowa"],
        "examples": ["centrala z resetem temperatury nawiewu wg najzimniejszej strefy"],
    },
    "V-3": {
        "friendly_name": "Free-cooling wentylacja mechaniczna",
        "purpose": "Chlodzenie budynku swiezym, chlodnym powietrzem zewnetrznym (zamiast agregatu), gdy warunki na to pozwalaja.",
        "technical": "Wykorzystanie powietrza zewnetrznego do chlodzenia przez zwiekszenie strumienia swiezego powietrza/obejscie odzysku, sterowane wg temperatur i entalpii; od braku, przez sterowanie temperaturowe, po sterowanie entalpiowe.",
        "energy_significance": "Free-cooling zastepuje prace agregatu chlodniczego w okresach przejsciowych i noca — duze oszczednosci energii chlodniczej.",
        "level_notes": {
            0: "Brak free-coolingu.",
            1: "Free-cooling sterowany temperatura (economizer temperaturowy).",
            2: "Free-cooling sterowany entalpia (uwzglednia wilgotnosc).",
            3: "Zaawansowany free-cooling z optymalizacja i nocnym przewietrzaniem.",
        },
        "technologies": ["economizer (temperaturowy/entalpiowy)", "night purge (przewietrzanie nocne)", "przepustnice powietrza zewnetrznego", "sterowniki central"],
        "devices": ["przepustnice powietrza zewnetrznego/wywiewu", "czujniki temperatury i wilgotnosci (zewn./wewn.)", "sterownik centrali"],
        "audit_verification": ["sprawdz mozliwosc zwiekszenia strumienia swiezego powietrza", "ustal logike free-coolingu (temperatura/entalpia)", "zweryfikuj nocne przewietrzanie (wyzsze poziomy)"],
        "evidence": ["konfiguracja economizera", "trendy przepustnic i temperatur", "schemat central z przepustnicami"],
        "common_mistakes": ["brak free-coolingu mimo mozliwosci", "economizer temperaturowy w klimacie wilgotnym (bez entalpii)", "kolizja z odzyskiem ciepla"],
        "limitations": ["zalezny od klimatu i warunkow", "wymaga wystarczajacej wydajnosci central i przepustnic"],
        "dependencies": ["V-2c (odzysk/by-pass)", "V-1c (przeplyw)", "C-1a (koordynacja z chlodzeniem)"],
        "cross_domain_impact": ["chlodzenie (redukcja pracy agregatow)", "elektrycznosc (oszczednosc energii chlodniczej)"],
        "modernization": ["wdrozenie economizera entalpiowego", "aktywacja nocnego przewietrzania", "koordynacja z chlodzeniem mechanicznym"],
        "examples": ["biurowiec z free-coolingiem w okresach przejsciowych i night purge latem"],
    },
    "V-6": {
        "friendly_name": "Raportowanie jakosci powietrza (IAQ)",
        "purpose": "Monitorowanie i informowanie o jakosci powietrza wewnetrznego (CO2, wilgotnosc, VOC), aby zapewnic zdrowe warunki i wesprzec sterowanie wentylacja.",
        "technical": "Zbieranie i prezentacja parametrow IAQ; wyzsze poziomy z historia, benchmarkiem i alarmami przekroczen oraz informacja dla uzytkownikow.",
        "energy_significance": "Dane IAQ umozliwiaja wentylacje na zadanie (nie wiecej niz trzeba) — poprawa zdrowia bez przewentylowywania i marnowania energii.",
        "level_notes": {
            0: "Brak raportowania IAQ.",
            1: "Podstawowy pomiar/wskazanie IAQ (np. CO2).",
            2: "Rejestracja i historia parametrow IAQ.",
            3: "Analiza/alarmy przekroczen i informacja dla uzytkownikow.",
        },
        "technologies": ["czujniki CO2/VOC/wilgotnosci/PM", "historian/trendy", "dashboardy IAQ", "wyswietlacze dla uzytkownikow"],
        "devices": ["czujniki jakosci powietrza", "wyswietlacze/sygnalizacja IAQ", "koncentrator danych"],
        "audit_verification": ["sprawdz obecnosc czujnikow IAQ i archiwizacje danych", "zweryfikuj alarmy przekroczen", "ustal informowanie uzytkownikow (poziom 3)"],
        "evidence": ["dashboardy IAQ", "eksport trendow CO2/wilgotnosci", "lista czujnikow"],
        "common_mistakes": ["czujniki bez kalibracji (dryft)", "dane bez alarmow/dzialania", "brak pomiaru w reprezentatywnych strefach"],
        "limitations": ["dryft i zywotnosc czujnikow", "koniecznosc utrzymania systemu"],
        "dependencies": ["V-1a (DCV wykorzystuje dane IAQ)", "MC-13 (centralne raportowanie)", "MC-9 (obecnosc)"],
        "cross_domain_impact": ["monitoring i sterowanie (dane do sterowania i raportow)", "zdrowie/komfort uzytkownikow"],
        "modernization": ["montaz czujnikow CO2/VOC w strefach", "dashboard i alarmy IAQ", "powiazanie IAQ ze sterowaniem DCV"],
        "examples": ["szkola z monitoringiem CO2 i sygnalizacja dla nauczycieli", "biuro z dashboardem IAQ i alarmami"],
    },
}
