-- SRI seed — czesc 8/8 (wygenerowana przez store/sri/_split_seed.py)
-- Uruchom PO migracji 096_sri_catalogue.sql, po kolei: 01, 02, ...
-- Idempotentny (ON CONFLICT DO NOTHING) — mozna uruchomic ponownie bezpiecznie.

do $$
declare
  v_mid uuid;
  v_cat uuid;
begin
  select id into v_mid from public.sri_methodology_versions where code = 'eu-2020-2155-v1';
  select id into v_cat from public.sri_catalogues where methodology_version_id = v_mid and code = 'eu-method-b-2020-v4.5';
  if v_mid is null or v_cat is null then
    raise exception 'Brak metodologii/katalogu — uruchom najpierw migracje 096.';
  end if;

  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='cooling'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='comfort'), 'non_residential', 'south_east_europe', 0.16) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='cooling'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='convenience'), 'non_residential', 'south_east_europe', 0.1) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='cooling'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='health_wellbeing_accessibility'), 'non_residential', 'south_east_europe', 0.16) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='cooling'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='maintenance_and_fault_prediction'), 'non_residential', 'south_east_europe', 0.0846345609) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='cooling'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='information_to_occupants'), 'non_residential', 'south_east_europe', 0.1142857143) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='ventilation'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='energy_efficiency'), 'non_residential', 'south_east_europe', 0.1505781965) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='ventilation'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='energy_flexibility_and_storage'), 'non_residential', 'south_east_europe', 0.0) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='ventilation'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='comfort'), 'non_residential', 'south_east_europe', 0.16) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='ventilation'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='convenience'), 'non_residential', 'south_east_europe', 0.1) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='ventilation'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='health_wellbeing_accessibility'), 'non_residential', 'south_east_europe', 0.16) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='ventilation'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='maintenance_and_fault_prediction'), 'non_residential', 'south_east_europe', 0.1708653897) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='ventilation'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='information_to_occupants'), 'non_residential', 'south_east_europe', 0.1142857143) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='lighting'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='energy_efficiency'), 'non_residential', 'south_east_europe', 0.0890490163) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='lighting'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='energy_flexibility_and_storage'), 'non_residential', 'south_east_europe', 0.0) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='lighting'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='comfort'), 'non_residential', 'south_east_europe', 0.16) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='lighting'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='convenience'), 'non_residential', 'south_east_europe', 0.1) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='lighting'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='health_wellbeing_accessibility'), 'non_residential', 'south_east_europe', 0.16) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='lighting'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='maintenance_and_fault_prediction'), 'non_residential', 'south_east_europe', 0.0) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='lighting'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='information_to_occupants'), 'non_residential', 'south_east_europe', 0.0) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electricity'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='energy_efficiency'), 'non_residential', 'south_east_europe', 0.033001247) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electricity'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='energy_flexibility_and_storage'), 'non_residential', 'south_east_europe', 0.0484957973) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electricity'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='comfort'), 'non_residential', 'south_east_europe', 0.0) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electricity'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='convenience'), 'non_residential', 'south_east_europe', 0.1) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electricity'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='health_wellbeing_accessibility'), 'non_residential', 'south_east_europe', 0.0) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electricity'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='maintenance_and_fault_prediction'), 'non_residential', 'south_east_europe', 0.0374474596) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electricity'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='information_to_occupants'), 'non_residential', 'south_east_europe', 0.1142857143) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='dynamic_building_envelope'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='energy_efficiency'), 'non_residential', 'south_east_europe', 0.05) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='dynamic_building_envelope'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='energy_flexibility_and_storage'), 'non_residential', 'south_east_europe', 0.0) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='dynamic_building_envelope'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='comfort'), 'non_residential', 'south_east_europe', 0.16) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='dynamic_building_envelope'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='convenience'), 'non_residential', 'south_east_europe', 0.1) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='dynamic_building_envelope'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='health_wellbeing_accessibility'), 'non_residential', 'south_east_europe', 0.16) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='dynamic_building_envelope'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='maintenance_and_fault_prediction'), 'non_residential', 'south_east_europe', 0.05) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='dynamic_building_envelope'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='information_to_occupants'), 'non_residential', 'south_east_europe', 0.1142857143) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electric_vehicle_charging'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='energy_efficiency'), 'non_residential', 'south_east_europe', 0.0) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electric_vehicle_charging'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='energy_flexibility_and_storage'), 'non_residential', 'south_east_europe', 0.05) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electric_vehicle_charging'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='comfort'), 'non_residential', 'south_east_europe', 0.0) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electric_vehicle_charging'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='convenience'), 'non_residential', 'south_east_europe', 0.1) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electric_vehicle_charging'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='health_wellbeing_accessibility'), 'non_residential', 'south_east_europe', 0.0) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electric_vehicle_charging'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='maintenance_and_fault_prediction'), 'non_residential', 'south_east_europe', 0.0) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='electric_vehicle_charging'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='information_to_occupants'), 'non_residential', 'south_east_europe', 0.1142857143) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='monitoring_and_control'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='energy_efficiency'), 'non_residential', 'south_east_europe', 0.2) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='monitoring_and_control'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='energy_flexibility_and_storage'), 'non_residential', 'south_east_europe', 0.2) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='monitoring_and_control'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='comfort'), 'non_residential', 'south_east_europe', 0.2) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='monitoring_and_control'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='convenience'), 'non_residential', 'south_east_europe', 0.2) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='monitoring_and_control'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='health_wellbeing_accessibility'), 'non_residential', 'south_east_europe', 0.2) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='monitoring_and_control'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='maintenance_and_fault_prediction'), 'non_residential', 'south_east_europe', 0.2) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;
  insert into public.sri_domain_impact_weights (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone, weight)
  values (v_mid, (select id from public.sri_technical_domains where methodology_version_id=v_mid and code='monitoring_and_control'), (select id from public.sri_impact_criteria where methodology_version_id=v_mid and code='information_to_occupants'), 'non_residential', 'south_east_europe', 0.2) on conflict (methodology_version_id, domain_id, impact_criterion_id, building_type, climate_zone) do nothing;

end $$;
